-- MY GYM London - migration: meals library (recipes, foods, 7-day meal plans)
-- Source: the PTPN meal files (seed_common_meals.sql and seed_meal_plans.sql), no photos.
-- Paste into Supabase Dashboard -> SQL Editor -> Run (safe to re-run: ids come from the names, so repeats are skipped).
-- Signed-in members can read these tables; nobody can change them from the app.

begin;

create table if not exists public.foods (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  serving_label text not null default '100 g',
  serving_g numeric not null default 100 check (serving_g > 0),
  kcal numeric not null default 0,        -- macros are per 100 g
  protein numeric not null default 0,
  carbs numeric not null default 0,
  fat numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.recipes (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  meal_type text not null default 'lunch' check (meal_type in ('breakfast','lunch','dinner','snack')),
  description text not null default '',
  prep_min int,
  kcal numeric not null default 0,        -- per serving
  protein numeric not null default 0,
  carbs numeric not null default 0,
  fat numeric not null default 0,
  ingredients text[] not null default '{}',
  steps text[] not null default '{}',
  tags text[] not null default '{}',
  image_url text,                         -- not used by the app (photos are off)
  created_at timestamptz not null default now()
);

create table if not exists public.meal_plan_templates (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  goal text not null default 'Balanced',
  kcal int not null default 2000,
  description text not null default '',
  image_url text,
  plan_no int,
  created_at timestamptz not null default now()
);

create table if not exists public.meal_plan_template_items (
  id uuid primary key default gen_random_uuid(),
  template_id uuid not null references public.meal_plan_templates(id) on delete cascade,
  day int not null check (day between 1 and 7),
  meal_type text not null check (meal_type in ('breakfast','lunch','dinner','snack')),
  recipe_id uuid not null references public.recipes(id) on delete cascade,
  servings numeric not null default 1 check (servings > 0),
  sort int not null default 0
);
create index if not exists meal_plan_template_items_tpl on public.meal_plan_template_items (template_id, day);

alter table public.foods enable row level security;
alter table public.recipes enable row level security;
alter table public.meal_plan_templates enable row level security;
alter table public.meal_plan_template_items enable row level security;
drop policy if exists foods_read on public.foods;
create policy foods_read on public.foods for select to authenticated using (true);
drop policy if exists recipes_read on public.recipes;
create policy recipes_read on public.recipes for select to authenticated using (true);
drop policy if exists meal_plans_read on public.meal_plan_templates;
create policy meal_plans_read on public.meal_plan_templates for select to authenticated using (true);
drop policy if exists meal_plan_items_read on public.meal_plan_template_items;
create policy meal_plan_items_read on public.meal_plan_template_items for select to authenticated using (true);
revoke all on public.foods, public.recipes, public.meal_plan_templates, public.meal_plan_template_items from anon, authenticated;
grant select on public.foods, public.recipes, public.meal_plan_templates, public.meal_plan_template_items to authenticated;

create or replace function pg_temp.sid(t text) returns uuid language sql immutable as $$ select md5(t)::uuid $$;


insert into public.foods (id, name, serving_label, serving_g, kcal, protein, carbs, fat) values
(pg_temp.sid('food:Mixed nuts'),'Mixed nuts','1 handful (30 g)',30,607,20,21,54),
(pg_temp.sid('food:Popcorn, air-popped'),'Popcorn, air-popped','1 bowl (25 g)',25,387,12,78,4.5),
(pg_temp.sid('food:Wholemeal crackers'),'Wholemeal crackers','4 crackers (25 g)',25,413,11,64,12),
(pg_temp.sid('food:Baked beans'),'Baked beans','1/2 can (200 g)',200,90,4.7,15.5,0.4),
(pg_temp.sid('food:Potato, baked'),'Potato, baked','1 medium (220 g)',220,93,2.5,21,0.1),
(pg_temp.sid('food:Olives'),'Olives','10 olives (40 g)',40,115,0.8,6,11)
on conflict (id) do nothing;

insert into public.recipes (id, name, meal_type, description, prep_min, kcal, protein, carbs, fat, ingredients, steps, tags, image_url) values
(pg_temp.sid('recipe:Banana and peanut butter porridge'),'Banana and peanut butter porridge','breakfast','Creamy oats cooked in milk with sliced banana and a spoon of peanut butter.',8,541,23.5,81.4,16.2,array['60 g oats, dry','250 ml milk, semi-skimmed','100 g banana','15 g peanut butter','5 g honey','1/4 tsp ground cinnamon']::text[],array['Heat the oats and milk in a pan, stirring, for 4 to 5 minutes until thick.','Pour into a bowl and top with sliced banana.','Swirl in the peanut butter and honey and finish with cinnamon.']::text[],array['quick','high fibre']::text[],null),
(pg_temp.sid('recipe:Poached eggs on toast with spinach'),'Poached eggs on toast with spinach','breakfast','Three soft eggs on wholemeal toast over wilted spinach.',10,437,29.8,31.9,20.9,array['150 g eggs, whole','70 g wholemeal bread','60 g spinach','5 g butter','1 tsp white vinegar','black pepper to taste']::text[],array['Wilt the spinach in a dry pan for a minute and set aside.','Poach the eggs in barely simmering water with a splash of vinegar for 3 minutes.','Toast and lightly butter the bread, top with spinach and the eggs.']::text[],array['high protein','quick']::text[],null),
(pg_temp.sid('recipe:Avocado and egg toast'),'Avocado and egg toast','breakfast','Mashed avocado and tomato on wholemeal toast with a fried or boiled egg.',10,439,23.6,37.7,22.3,array['70 g wholemeal bread','70 g avocado','100 g eggs, whole','60 g tomato','1 tsp lemon juice','pinch of chilli flakes']::text[],array['Toast the bread and mash the avocado with lemon juice and a pinch of salt.','Cook the eggs the way you like them.','Spread the avocado on the toast and top with tomato, the eggs and chilli flakes.']::text[],array['vegetarian','quick']::text[],null),
(pg_temp.sid('recipe:Banana and spinach protein smoothie'),'Banana and spinach protein smoothie','breakfast','A thick green smoothie with whey and oats that keeps you full.',5,468,40.1,62.8,8.6,array['120 g banana','40 g spinach','250 ml milk, semi-skimmed','30 g whey protein powder','30 g oats, dry','4 ice cubes']::text[],array['Add the milk, banana, spinach, whey and oats to a blender.','Blend with a handful of ice until completely smooth.','Drink straight away.']::text[],array['high protein','no cook']::text[],null),
(pg_temp.sid('recipe:Egg breakfast burrito'),'Egg breakfast burrito','breakfast','Scrambled eggs, black beans and cheese rolled in a warm tortilla.',12,562,33.7,50.5,24.5,array['62 g tortilla wrap','150 g eggs, whole','60 g black beans, cooked','40 g salsa','15 g cheddar cheese','1/2 tsp smoked paprika']::text[],array['Warm the beans with a pinch of paprika.','Scramble the eggs in a non-stick pan until just set.','Fill the tortilla with eggs, beans, cheese and salsa, fold in the ends and roll.']::text[],array['high protein','mexican']::text[],null),
(pg_temp.sid('recipe:Veggie egg muffins'),'Veggie egg muffins','breakfast','Baked egg cups packed with pepper and spinach, served with toast.',30,501,37.8,21.1,28.8,array['200 g eggs, whole','60 g bell pepper','40 g spinach','25 g cheddar cheese','35 g wholemeal bread','black pepper to taste']::text[],array['Heat the oven to 180C and grease a muffin tin.','Whisk the eggs, then stir in chopped pepper, spinach and cheese and pour into the tin.','Bake for 18 to 20 minutes and serve with toast. They keep for three days in the fridge.']::text[],array['meal prep','high protein']::text[],null),
(pg_temp.sid('recipe:Berry chia pudding'),'Berry chia pudding','breakfast','Make it the night before: chia soaked in milk and yogurt, topped with berries.',5,425,24.9,46.0,18.3,array['30 g chia seeds','200 ml milk, semi-skimmed','100 g Greek yogurt 0% fat','80 g blueberries','8 g honey','10 g almonds','1/2 tsp vanilla extract']::text[],array['Stir the chia, milk, yogurt, honey and vanilla together in a jar.','Leave in the fridge overnight, stirring once after 10 minutes.','Top with blueberries and chopped almonds.']::text[],array['meal prep','no cook']::text[],null),
(pg_temp.sid('recipe:Chicken, rice and broccoli meal prep box'),'Chicken, rice and broccoli meal prep box','lunch','The classic lunch box: plain, filling and easy to batch for the week.',25,528,53.9,49.9,11.3,array['150 g chicken breast, cooked','150 g white rice, cooked','120 g broccoli','5 g olive oil','1/2 lemon','1/2 tsp garlic powder','black pepper to taste']::text[],array['Season the chicken with garlic powder and pepper and bake or grill until cooked through.','Steam the broccoli for 4 minutes.','Pack with the rice, drizzle the oil and squeeze over lemon.']::text[],array['meal prep','high protein']::text[],null),
(pg_temp.sid('recipe:Chicken salad sandwich'),'Chicken salad sandwich','lunch','Shredded chicken in a light yogurt and mustard dressing on wholemeal bread.',10,465,46.0,54.9,7.0,array['80 g wholemeal bread','100 g chicken breast, cooked','30 g Greek yogurt 0% fat','30 g mixed salad leaves','50 g tomato','5 g Dijon mustard','130 g apple','black pepper to taste']::text[],array['Mix the shredded chicken with the yogurt, mustard and pepper.','Layer onto the bread with leaves and sliced tomato.','Serve with the apple.']::text[],array['quick','high protein']::text[],null),
(pg_temp.sid('recipe:Cheesy bean jacket potato'),'Cheesy bean jacket potato','lunch','A baked potato topped with warm baked beans and a little melted cheese.',55,494,21.4,77.3,10.8,array['250 g potato, baked','150 g baked beans','30 g cheddar cheese','40 g mixed salad leaves','black pepper to taste']::text[],array['Prick the potato and bake at 200C for about 50 minutes (or microwave for 8 to 10 minutes).','Warm the beans.','Split the potato, pile on the beans and cheese and serve with the leaves.']::text[],array['vegetarian','budget']::text[],null),
(pg_temp.sid('recipe:Greek salad with grilled chicken'),'Greek salad with grilled chicken','lunch','Crisp cucumber, tomato, feta and olives with sliced chicken and a little bread.',15,569,53.3,29.9,26.1,array['130 g chicken breast, cooked','100 g cucumber','120 g tomato','40 g feta','30 g olives','20 g onion','8 g olive oil','40 g wholemeal bread','1/2 tsp dried oregano','1 tbsp lemon juice']::text[],array['Chop the cucumber, tomato and onion into chunks and add the olives.','Toss with olive oil, lemon juice and oregano and crumble over the feta.','Top with sliced chicken and serve with the bread.']::text[],array['high protein','mediterranean']::text[],null),
(pg_temp.sid('recipe:Egg and avocado wrap'),'Egg and avocado wrap','lunch','Chopped boiled eggs, avocado and spinach in a tortilla.',10,539,29.7,42.6,28.4,array['62 g tortilla wrap','150 g eggs, whole','60 g avocado','30 g spinach','60 g tomato','30 g Greek yogurt 0% fat','1 tsp lemon juice','black pepper to taste']::text[],array['Boil the eggs for 8 minutes, cool and chop.','Mash the avocado with the yogurt and lemon juice and mix in the eggs.','Spoon onto the wrap with spinach and tomato and roll up.']::text[],array['vegetarian','quick']::text[],null),
(pg_temp.sid('recipe:Minestrone soup with wholemeal bread'),'Minestrone soup with wholemeal bread','lunch','A thick vegetable, bean and pasta soup with a slice of bread.',30,567,28.1,90.9,11.1,array['100 g kidney beans, cooked','200 g chopped tomatoes, canned','60 g carrot','80 g courgette','80 g pasta, cooked','40 g onion','50 g green beans','8 g parmesan','50 g wholemeal bread','5 g olive oil','400 ml vegetable stock','1 clove garlic','1 tsp dried basil']::text[],array['Soften the onion, carrot and garlic in the oil for 5 minutes.','Add the tomatoes, stock, courgette, green beans and kidney beans and simmer for 15 minutes.','Stir in the cooked pasta, serve with parmesan and the bread.']::text[],array['vegetarian','one pot']::text[],null),
(pg_temp.sid('recipe:Tuna and sweetcorn pasta'),'Tuna and sweetcorn pasta','lunch','A quick yogurt-dressed pasta with tuna, sweetcorn and tomatoes.',15,604,52.0,79.3,9.3,array['200 g pasta, cooked','120 g tuna, canned in water, drained','60 g sweetcorn','60 g Greek yogurt 0% fat','80 g tomato','5 g olive oil','20 g mixed salad leaves','1 tbsp lemon juice','black pepper to taste']::text[],array['Cook the pasta, drain and let it cool a little.','Mix the yogurt with lemon juice, oil and pepper.','Toss through the pasta with the tuna, sweetcorn and chopped tomato and serve on the leaves.']::text[],array['quick','high protein']::text[],null),
(pg_temp.sid('recipe:Baked chicken with sweet potato and green beans'),'Baked chicken with sweet potato and green beans','dinner','Simple oven-baked chicken breast with roasted sweet potato wedges.',40,567,62.0,49.8,13.1,array['180 g chicken breast, cooked','200 g sweet potato, baked','120 g green beans','6 g olive oil','1/2 tsp paprika','1/2 tsp garlic powder','black pepper to taste']::text[],array['Heat the oven to 200C. Toss the sweet potato wedges in half the oil and roast for 15 minutes.','Rub the chicken with the rest of the oil and the spices, add to the tray and roast for 20 to 25 minutes.','Steam the green beans and serve everything together.']::text[],array['high protein','one pan']::text[],null),
(pg_temp.sid('recipe:Chicken fajitas'),'Chicken fajitas','dinner','Sizzling chicken, peppers and onion in warm tortillas with salsa and yogurt.',25,736,60.7,67.5,24.1,array['140 g chicken breast, cooked','120 g bell pepper','60 g onion','93 g tortilla wrap','40 g salsa','40 g Greek yogurt 0% fat','10 g cheddar cheese','25 g avocado','4 g olive oil','2 tsp fajita seasoning','1/2 lime']::text[],array['Slice the chicken, peppers and onion into strips and toss with the oil and seasoning.','Fry in a hot pan for 6 to 8 minutes until charred.','Fill the warm tortillas and top with salsa, yogurt, cheese and avocado.']::text[],array['high protein','mexican']::text[],null),
(pg_temp.sid('recipe:Lean shepherd''s pie'),'Lean shepherd''s pie','dinner','Lean beef and vegetable filling under a light mash topping.',50,641,52.8,74.1,15.2,array['150 g beef mince 5% fat, cooked','250 g potato, boiled','60 g carrot','60 g peas, frozen','50 g onion','100 g chopped tomatoes, canned','30 ml milk, semi-skimmed','10 g cheddar cheese','1 tbsp worcestershire sauce','150 ml beef stock','1/2 tsp dried thyme']::text[],array['Brown the mince with the onion and carrot, then add the tomatoes, stock, worcestershire and thyme and simmer for 15 minutes with the peas.','Mash the potato with the milk and pepper.','Spoon the mince into a dish, cover with the mash and cheese and bake at 200C for 20 minutes.']::text[],array['comfort','meal prep']::text[],null),
(pg_temp.sid('recipe:Grilled salmon with new potatoes and asparagus'),'Grilled salmon with new potatoes and asparagus','dinner','A fillet of salmon with buttery potatoes and charred asparagus.',25,551,39.4,44.7,23.3,array['150 g salmon fillet, cooked','200 g potato, boiled','120 g asparagus','5 g olive oil','1/2 lemon','1 tbsp fresh dill','black pepper to taste']::text[],array['Boil the potatoes for 15 minutes.','Grill or pan-fry the salmon for 4 minutes each side and griddle the asparagus with the oil.','Serve with lemon and dill.']::text[],array['omega-3','high protein']::text[],null),
(pg_temp.sid('recipe:Stuffed peppers with beef and rice'),'Stuffed peppers with beef and rice','dinner','Roasted peppers filled with seasoned mince, rice and melted mozzarella.',45,558,47.0,56.8,14.8,array['250 g bell pepper','120 g beef mince 5% fat, cooked','120 g white rice, cooked','100 g chopped tomatoes, canned','40 g onion','30 g mozzarella','1 tsp smoked paprika','1 clove garlic']::text[],array['Halve the peppers and remove the seeds.','Mix the mince, rice, tomatoes, onion, garlic and paprika and spoon into the pepper halves.','Top with mozzarella and bake at 200C for 30 minutes.']::text[],array['high protein','meal prep']::text[],null),
(pg_temp.sid('recipe:Vegetable and bean chilli with rice'),'Vegetable and bean chilli with rice','dinner','A big pot of two-bean chilli with pepper and courgette.',35,634,33.1,104.2,10.2,array['100 g kidney beans, cooked','80 g black beans, cooked','200 g chopped tomatoes, canned','100 g bell pepper','50 g onion','80 g courgette','160 g brown rice, cooked','20 g cheddar cheese','30 g Greek yogurt 0% fat','1 tsp chilli powder','1 tsp ground cumin','1 clove garlic']::text[],array['Soften the onion, pepper and courgette with garlic, chilli and cumin.','Add the tomatoes and beans and simmer for 20 minutes.','Serve over rice with grated cheese and a spoon of yogurt.']::text[],array['vegetarian','meal prep']::text[],null),
(pg_temp.sid('recipe:Grilled pork loin with roast potatoes and broccoli'),'Grilled pork loin with roast potatoes and broccoli','dinner','Lean pork with crisp roast potatoes and steamed broccoli.',40,546,51.7,51.9,14.7,array['170 g pork tenderloin, cooked','220 g potato, boiled','120 g broccoli','8 g olive oil','1 sprig rosemary','1 clove garlic','black pepper to taste']::text[],array['Roast the halved potatoes with half the oil and rosemary at 210C for 35 minutes.','Rub the pork with the remaining oil, garlic and pepper and grill or roast for 20 minutes, then rest and slice.','Steam the broccoli and serve together.']::text[],array['high protein','weekend']::text[],null),
(pg_temp.sid('recipe:Banana'),'Banana','snack','The easiest grab-and-go snack.',1,107,1.3,27.4,0.4,array['120 g banana']::text[],array['Peel and eat. Pair with a handful of nuts if you need more staying power.']::text[],array['no cook','quick']::text[],null),
(pg_temp.sid('recipe:Handful of mixed nuts'),'Handful of mixed nuts','snack','A palm-sized portion of almonds, walnuts, cashews and peanuts.',1,182,6.0,6.3,16.2,array['30 g mixed nuts']::text[],array['Measure out 30 g so it stays a snack and not a meal.']::text[],array['no cook','healthy fats']::text[],null),
(pg_temp.sid('recipe:Cheese and wholemeal crackers'),'Cheese and wholemeal crackers','snack','A small cheddar slice stack on wholemeal crackers with a few grapes.',3,266,10.7,27.2,13.0,array['30 g cheddar cheese','25 g wholemeal crackers','60 g grapes']::text[],array['Slice the cheese and lay it on the crackers.','Serve with the grapes.']::text[],array['quick','no cook']::text[],null),
(pg_temp.sid('recipe:Protein bar'),'Protein bar','snack','A ready-made bar for when you are out and about.',1,210,19.8,21.0,6.0,array['60 g protein bar']::text[],array['Check the label: aim for around 20 g protein and under 4 g sugar.']::text[],array['no cook','high protein']::text[],null),
(pg_temp.sid('recipe:Air-popped popcorn'),'Air-popped popcorn','snack','A big bowl of plain popcorn for very few calories.',5,97,3.0,19.5,1.1,array['25 g popcorn, air-popped','pinch of salt']::text[],array['Pop the kernels in an air popper or a covered pan with no oil.','Season with a pinch of salt.']::text[],array['low calorie','high fibre']::text[],null),
(pg_temp.sid('recipe:Clementines'),'Clementines','snack','Two easy-peel citrus fruits with a good dose of vitamin C.',2,75,1.4,18.9,0.2,array['160 g orange']::text[],array['Peel and eat.']::text[],array['no cook','low calorie']::text[],null),
(pg_temp.sid('recipe:Turkey and cucumber roll-ups'),'Turkey and cucumber roll-ups','snack','Sliced turkey rolled around cucumber and a little cream cheese.',5,120,20.2,3.4,2.7,array['60 g turkey breast, cooked','60 g cucumber','20 g light cream cheese','black pepper to taste']::text[],array['Spread the cream cheese on the turkey slices.','Lay a cucumber stick on each and roll up.']::text[],array['high protein','low calorie']::text[],null)
on conflict (id) do nothing;



insert into public.foods (id, name, serving_label, serving_g, kcal, protein, carbs, fat) values
(pg_temp.sid('food:Corn tortilla'),'Corn tortilla','1 tortilla (26 g)',26,218,5.7,44.6,2.9),
(pg_temp.sid('food:Flank steak, cooked'),'Flank steak, cooked','100 g',100,192,27.5,0,8.6),
(pg_temp.sid('food:Turkey mince, cooked'),'Turkey mince, cooked','100 g',100,190,27,0,9),
(pg_temp.sid('food:Chicken sausage, cooked'),'Chicken sausage, cooked','1 sausage (70 g)',70,170,16,3,10),
(pg_temp.sid('food:Soy sauce'),'Soy sauce','1 tbsp (15 g)',15,60,6,6,0),
(pg_temp.sid('food:Light coconut milk'),'Light coconut milk','100 ml',100,70,0.7,2.8,6.8),
(pg_temp.sid('food:Curry paste'),'Curry paste','1 tbsp (15 g)',15,100,2.5,14,3.5),
(pg_temp.sid('food:Gnocchi, cooked'),'Gnocchi, cooked','100 g',100,133,3.4,29,0.5),
(pg_temp.sid('food:Cheese tortellini, cooked'),'Cheese tortellini, cooked','100 g',100,200,8.5,29,5.5),
(pg_temp.sid('food:Chicken dumplings, cooked'),'Chicken dumplings, cooked','5 dumplings (100 g)',100,215,9.5,28,7),
(pg_temp.sid('food:Matzo meal'),'Matzo meal','30 g',30,365,10.5,78,1.5),
(pg_temp.sid('food:Cabbage'),'Cabbage','80 g',80,25,1.3,5.8,0.1),
(pg_temp.sid('food:Braising beef, cooked lean'),'Braising beef, cooked lean','100 g',100,230,30,0,12),
(pg_temp.sid('food:Light cream cheese'),'Light cream cheese','30 g',30,150,9,6,10),
(pg_temp.sid('food:Pizza dough, baked'),'Pizza dough, baked','100 g',100,270,9,50,3),
(pg_temp.sid('food:Wholemeal pita'),'Wholemeal pita','1 pita (60 g)',60,255,10,51,2.6),
(pg_temp.sid('food:Wholemeal burger bun'),'Wholemeal burger bun','1 bun (70 g)',70,265,11,46,4.5),
(pg_temp.sid('food:Salsa'),'Salsa','2 tbsp (40 g)',40,36,1.5,7.5,0.2),
(pg_temp.sid('food:Dijon mustard'),'Dijon mustard','1 tsp (5 g)',5,66,4,5.8,3.6),
(pg_temp.sid('food:BBQ sauce'),'BBQ sauce','1 tbsp (17 g)',17,150,0.8,36,0.6),
(pg_temp.sid('food:Plain flour'),'Plain flour','30 g',30,364,10,76,1),
(pg_temp.sid('food:Breadcrumbs'),'Breadcrumbs','30 g',30,395,13,72,5),
(pg_temp.sid('food:Tortilla chips'),'Tortilla chips','30 g',30,490,7,63,24),
(pg_temp.sid('food:Tomato ketchup'),'Tomato ketchup','1 tbsp (17 g)',17,100,1.2,25,0.1)
on conflict (id) do nothing;

insert into public.recipes (id, name, meal_type, description, prep_min, kcal, protein, carbs, fat, ingredients, steps, tags, image_url) values
(pg_temp.sid('recipe:Lean carne asada tacos'),'Lean carne asada tacos','dinner','Citrus-marinated flank steak in corn tortillas with fresh toppings.',25,581,51.2,48.3,21.4,array['150 g flank steak, cooked','78 g corn tortilla','40 g onion','60 g tomato','40 g avocado','40 g salsa','30 g Greek yogurt 0% fat','1 tbsp lime juice','1 clove garlic','1/2 tsp ground cumin','1 tbsp fresh coriander']::text[],array['Marinate the steak in lime juice, garlic and cumin for 30 minutes.','Sear in a hot pan for 3 to 4 minutes per side, rest, then slice thinly across the grain.','Warm the tortillas and fill with steak, onion, tomato, avocado, salsa and a spoon of yogurt.']::text[],array['high protein','mexican']::text[],null),
(pg_temp.sid('recipe:Lighter General Tso''s chicken'),'Lighter General Tso''s chicken','dinner','Sticky ginger-soy chicken with broccoli, baked instead of deep-fried.',25,622,61.4,64.5,12.1,array['170 g chicken breast, cooked','120 g broccoli','150 g white rice, cooked','15 g soy sauce','12 g honey','40 g carrot','5 g olive oil','1 tsp grated fresh ginger','1 clove garlic','1 tbsp rice vinegar','pinch of chilli flakes']::text[],array['Cube the chicken and brown it in a hot pan with the oil.','Stir together soy sauce, honey, vinegar, ginger and garlic, pour over and simmer until glossy.','Steam the broccoli and carrot, then serve everything over rice.']::text[],array['high protein','asian']::text[],null),
(pg_temp.sid('recipe:Creamy tomato tortellini soup'),'Creamy tomato tortellini soup','dinner','Tomato soup enriched with a little cream cheese, cheese tortellini and spinach.',25,556,51.5,49.8,16.2,array['120 g cheese tortellini, cooked','200 g chopped tomatoes, canned','60 g spinach','30 g light cream cheese','100 g chicken breast, cooked','40 g onion','8 g parmesan','1 clove garlic','300 ml chicken or vegetable stock','1 tsp dried basil']::text[],array['Soften the onion and garlic, add the tomatoes and a cup of stock and simmer for 10 minutes.','Blend until smooth, stir in the cream cheese, then add the tortellini and shredded chicken.','Wilt in the spinach and finish with parmesan.']::text[],array['comfort','one pot']::text[],null),
(pg_temp.sid('recipe:Ham and egg fried rice'),'Ham and egg fried rice','dinner','Fast fried rice built on lean ham, eggs and plenty of veg.',15,659,40.6,72.6,21.7,array['100 g ham, sliced','200 g white rice, cooked','100 g eggs, whole','60 g peas, frozen','50 g carrot','15 g soy sauce','8 g olive oil','2 spring onions','1 clove garlic']::text[],array['Heat the oil in a wok and scramble the eggs, then set aside.','Stir-fry the carrot, peas and chopped ham for 2 minutes.','Add the cold rice, soy sauce and eggs and toss until piping hot.']::text[],array['quick','meal prep']::text[],null),
(pg_temp.sid('recipe:Honey mustard chicken with potatoes'),'Honey mustard chicken with potatoes','dinner','Sheet-pan chicken with a light honey and mustard glaze.',35,608,62.4,59.1,13.5,array['180 g chicken breast, cooked','12 g honey','15 g Dijon mustard','200 g potato, boiled','120 g green beans','6 g olive oil','1 clove garlic','1/2 tsp paprika']::text[],array['Whisk the honey, mustard, garlic and paprika and coat the chicken.','Roast the chicken and halved potatoes at 200C for 25 to 30 minutes.','Steam the green beans and serve alongside.']::text[],array['high protein','one pan']::text[],null),
(pg_temp.sid('recipe:Black bean and beef tostadas'),'Black bean and beef tostadas','dinner','Crisp corn tostadas piled with beans, lean beef and avocado.',20,658,46.9,71.5,22.3,array['78 g corn tortilla','120 g black beans, cooked','100 g beef mince 5% fat, cooked','50 g avocado','30 g mixed salad leaves','40 g salsa','15 g cheddar cheese','1/2 lime','1/2 tsp chilli powder']::text[],array['Bake the tortillas at 200C for 6 to 8 minutes until crisp.','Warm the beans and the beef mince with chilli powder.','Layer beans, beef, leaves, salsa, cheese and sliced avocado on each tostada.']::text[],array['mexican','high protein']::text[],null),
(pg_temp.sid('recipe:Southwest tortellini pasta salad'),'Southwest tortellini pasta salad','dinner','Cold tortellini tossed with beans, corn and a yogurt-salsa dressing.',20,705,61.0,85.7,13.8,array['150 g cheese tortellini, cooked','80 g black beans, cooked','60 g sweetcorn','80 g tomato','60 g bell pepper','60 g Greek yogurt 0% fat','40 g salsa','100 g chicken breast, cooked','1 tbsp lime juice','1 tbsp chopped coriander']::text[],array['Cook the tortellini, drain and cool under cold water.','Mix the yogurt, salsa and lime juice into a dressing.','Toss everything together with the chopped veg, beans and chicken.']::text[],array['meal prep','no cook']::text[],null),
(pg_temp.sid('recipe:Cajun chicken and sausage kebabs'),'Cajun chicken and sausage kebabs','dinner','Spiced chicken and chicken sausage skewers with peppers, served on rice.',30,663,61.2,57.2,19.1,array['140 g chicken breast, cooked','70 g chicken sausage, cooked','100 g bell pepper','80 g courgette','50 g onion','150 g white rice, cooked','6 g olive oil','2 tsp cajun seasoning','1/2 tsp garlic powder']::text[],array['Toss the chicken, sausage slices and chunks of veg with oil and cajun seasoning.','Thread onto skewers and grill or griddle for 12 to 15 minutes, turning often.','Serve on rice.']::text[],array['high protein','bbq']::text[],null),
(pg_temp.sid('recipe:Turkey meatballs arrabbiata'),'Turkey meatballs arrabbiata','dinner','Spicy tomato sauce with baked turkey meatballs over pasta.',35,741,61.3,74.7,20.9,array['150 g turkey mince, cooked','15 g breadcrumbs','25 g eggs, whole','200 g chopped tomatoes, canned','170 g pasta, cooked','40 g onion','8 g parmesan','2 cloves garlic','1/2 tsp chilli flakes','1 tsp dried oregano']::text[],array['Mix the turkey, breadcrumbs, egg and oregano, shape into balls and bake at 200C for 15 minutes.','Simmer the tomatoes with garlic, onion and chilli for 15 minutes.','Add the meatballs to the sauce and serve over pasta with parmesan.']::text[],array['high protein','meal prep']::text[],null),
(pg_temp.sid('recipe:Smash burger with tomato and lettuce'),'Smash burger with tomato and lettuce','dinner','Thin, crisp-edged beef patties on a wholemeal bun.',20,659,53.0,68.0,19.9,array['140 g beef mince 5% fat, cooked','70 g wholemeal burger bun','20 g cheddar cheese','60 g tomato','25 g mixed salad leaves','150 g potato, boiled','10 g tomato ketchup','1 tsp mustard','4 pickle slices']::text[],array['Roll the beef into two balls and smash flat in a very hot dry pan; season and cook 2 minutes per side.','Melt the cheese on top and toast the bun.','Build the burger and serve with roasted potato wedges.']::text[],array['high protein','quick']::text[],null),
(pg_temp.sid('recipe:Walking taco bowl'),'Walking taco bowl','dinner','All the walking taco flavour with a handful of chips and lots of toppings in a bowl.',20,690,59.1,54.0,27.8,array['140 g turkey mince, cooked','30 g tortilla chips','80 g black beans, cooked','50 g salsa','40 g mixed salad leaves','20 g cheddar cheese','40 g Greek yogurt 0% fat','50 g sweetcorn','2 tsp taco seasoning']::text[],array['Brown the turkey with taco seasoning and a splash of water.','Crush the chips into the bowl, then spoon over the turkey and beans.','Top with leaves, corn, salsa, cheese and yogurt.']::text[],array['fun','high protein']::text[],null),
(pg_temp.sid('recipe:Creamy chicken and gnocchi'),'Creamy chicken and gnocchi','dinner','Pan-fried gnocchi and chicken in a light creamy sauce with spinach.',25,666,63.9,58.4,19.1,array['150 g chicken breast, cooked','170 g gnocchi, cooked','60 g spinach','30 g light cream cheese','100 ml milk, semi-skimmed','10 g parmesan','5 g olive oil','1 clove garlic','black pepper to taste']::text[],array['Pan-fry the gnocchi in the oil until golden and set aside.','Warm the milk with the cream cheese and garlic until smooth, add the chicken and spinach.','Stir the gnocchi back in and top with parmesan.']::text[],array['comfort','high protein']::text[],null),
(pg_temp.sid('recipe:Hummus and edamame veggie wrap'),'Hummus and edamame veggie wrap','dinner','A crunchy plant-based wrap with edamame, hummus and raw veg.',10,723,32.9,90.7,27.5,array['124 g tortilla wrap','60 g hummus','100 g edamame','50 g carrot','60 g cucumber','30 g spinach','30 g feta','1 tsp lemon juice']::text[],array['Spread the hummus over the wraps.','Layer the edamame, grated carrot, cucumber, spinach and crumbled feta.','Squeeze over lemon, roll tightly and slice in half.']::text[],array['vegetarian','no cook']::text[],null),
(pg_temp.sid('recipe:Chicken red curry'),'Chicken red curry','dinner','Fragrant red curry with light coconut milk and vegetables.',30,654,58.3,63.3,17.7,array['160 g chicken breast, cooked','150 g light coconut milk','20 g curry paste','80 g bell pepper','80 g courgette','160 g white rice, cooked','60 g green beans','1 tsp fish sauce','1/2 lime','1 tbsp fresh basil']::text[],array['Fry the curry paste for a minute, pour in the coconut milk and a splash of water.','Add the chicken and vegetables and simmer for 12 minutes.','Finish with lime and basil and serve over rice.']::text[],array['high protein','asian']::text[],null),
(pg_temp.sid('recipe:Kung pao chicken'),'Kung pao chicken','dinner','Spicy-sweet stir-fry with peanuts, peppers and courgette.',25,739,66.1,61.9,24.4,array['170 g chicken breast, cooked','25 g peanuts','100 g bell pepper','80 g courgette','150 g white rice, cooked','15 g soy sauce','8 g honey','5 g olive oil','1 clove garlic','1 tsp grated fresh ginger','3 dried chillies','1 tbsp rice vinegar']::text[],array['Stir-fry the chicken in oil until browned, then add the vegetables and chillies.','Add soy sauce, honey, vinegar, garlic and ginger and toss for 2 minutes.','Stir through the peanuts and serve on rice.']::text[],array['high protein','asian']::text[],null),
(pg_temp.sid('recipe:Quinoa nourish bowl'),'Quinoa nourish bowl','dinner','A big plant-forward bowl: quinoa, roasted sweet potato, chickpeas and greens.',25,694,31.4,104.8,18.7,array['150 g quinoa, cooked','150 g sweet potato, baked','120 g chickpeas, cooked','40 g kale','50 g avocado','60 g Greek yogurt 0% fat','20 g feta','1 tbsp lemon juice','1/2 tsp paprika','1 tsp tahini (optional)']::text[],array['Roast the sweet potato cubes and chickpeas with paprika at 200C for 25 minutes.','Massage the kale with lemon juice.','Build the bowl on the quinoa and finish with sliced avocado, feta and a yogurt drizzle.']::text[],array['vegetarian','high fibre']::text[],null),
(pg_temp.sid('recipe:Mushroom and black bean tacos'),'Mushroom and black bean tacos','dinner','Savoury seared mushrooms and beans in warm corn tortillas.',20,621,33.1,79.1,22.7,array['78 g corn tortilla','200 g mushrooms','120 g black beans, cooked','50 g avocado','40 g salsa','50 g Greek yogurt 0% fat','20 g cheddar cheese','5 g olive oil','1/2 tsp smoked paprika','1/2 lime','1 tbsp chopped coriander']::text[],array['Sear the sliced mushrooms in the oil with smoked paprika until deeply browned.','Warm the beans and tortillas.','Fill with mushrooms and beans and top with avocado, salsa, yogurt and cheese.']::text[],array['vegetarian','mexican']::text[],null),
(pg_temp.sid('recipe:Turkey sloppy joes'),'Turkey sloppy joes','dinner','Saucy tomato-pepper turkey on a toasted wholemeal bun.',25,610,53.3,62.0,18.2,array['150 g turkey mince, cooked','70 g wholemeal burger bun','100 g chopped tomatoes, canned','40 g onion','60 g bell pepper','15 g tomato ketchup','80 g sweetcorn','1 tsp worcestershire sauce','1 clove garlic','1/2 tsp smoked paprika']::text[],array['Soften the onion and pepper, add the turkey and cook until browned.','Stir in the tomatoes, ketchup, worcestershire and spices and simmer for 10 minutes.','Pile onto the toasted bun and serve with corn.']::text[],array['high protein','family']::text[],null),
(pg_temp.sid('recipe:Chicken dumpling soup'),'Chicken dumpling soup','dinner','A light ginger broth with dumplings, greens and carrots.',20,667,48.0,77.6,17.5,array['180 g chicken dumplings, cooked','80 g chicken breast, cooked','50 g spinach','50 g carrot','10 g soy sauce','80 g egg noodles, cooked','300 ml chicken stock','1 tsp grated fresh ginger','2 spring onions']::text[],array['Simmer the stock with ginger, soy sauce and carrot for 8 minutes.','Add the dumplings and noodles and cook according to the pack.','Stir in the shredded chicken and spinach and top with spring onions.']::text[],array['comfort','quick']::text[],null),
(pg_temp.sid('recipe:Thai green curry chicken meatballs'),'Thai green curry chicken meatballs','dinner','Baked chicken meatballs in a green curry coconut sauce.',35,644,58.5,60.1,17.7,array['150 g chicken breast, cooked','10 g breadcrumbs','25 g eggs, whole','120 g light coconut milk','15 g curry paste','80 g broccoli','150 g white rice, cooked','1 tbsp chopped coriander','1/2 lime','1 tsp fish sauce']::text[],array['Mince or finely chop the chicken, mix with breadcrumbs, egg and coriander, shape into balls and bake for 15 minutes.','Simmer the curry paste with the coconut milk, add the broccoli and meatballs.','Serve with rice and a squeeze of lime.']::text[],array['high protein','asian']::text[],null),
(pg_temp.sid('recipe:Green chile chicken burritos'),'Green chile chicken burritos','dinner','Chicken, beans and rice rolled up and finished with salsa and a little cheese.',30,813,69.9,86.7,19.3,array['62 g tortilla wrap','140 g chicken breast, cooked','80 g black beans, cooked','100 g white rice, cooked','80 g salsa','25 g cheddar cheese','40 g Greek yogurt 0% fat','1 tbsp chopped green chiles','1/2 tsp ground cumin']::text[],array['Mix the chicken, beans and rice with cumin and a spoon of salsa.','Roll in the tortilla, top with the rest of the salsa and cheese and bake at 200C for 12 minutes.','Serve with a dollop of yogurt.']::text[],array['mexican','meal prep']::text[],null),
(pg_temp.sid('recipe:Chicken, bacon and avocado wrap'),'Chicken, bacon and avocado wrap','dinner','A satisfying wrap with just enough bacon for flavour.',10,692,57.1,66.0,22.7,array['62 g tortilla wrap','120 g chicken breast, cooked','50 g avocado','25 g bacon rashers, grilled','30 g spinach','60 g tomato','40 g Greek yogurt 0% fat','120 g sweet potato, baked','1 tsp lime juice','black pepper to taste']::text[],array['Mash the avocado with the yogurt and lime juice.','Spread over the wrap and add the chicken, crisp bacon, spinach and tomato.','Roll up and serve with baked sweet potato.']::text[],array['quick','high protein']::text[],null),
(pg_temp.sid('recipe:Loaded taco salad'),'Loaded taco salad','dinner','Crunchy leaves topped with seasoned beef, beans, corn and cheese.',20,605,54.1,52.3,21.5,array['120 g beef mince 5% fat, cooked','80 g mixed salad leaves','80 g black beans, cooked','50 g sweetcorn','80 g tomato','20 g cheddar cheese','50 g salsa','50 g Greek yogurt 0% fat','20 g tortilla chips','2 tsp taco seasoning','1/2 lime']::text[],array['Brown the beef with taco seasoning.','Pile the leaves into a bowl and add the beef, beans, corn and tomato.','Top with cheese, salsa, yogurt and crushed chips.']::text[],array['high protein','salad']::text[],null),
(pg_temp.sid('recipe:Chicken and matzo ball soup'),'Chicken and matzo ball soup','dinner','Classic comforting chicken soup with light matzo dumplings.',40,645,61.0,58.9,17.2,array['150 g chicken breast, cooked','40 g matzo meal','50 g eggs, whole','80 g carrot','50 g onion','60 g egg noodles, cooked','5 g olive oil','400 ml chicken stock','1 celery stick','1 tbsp fresh dill']::text[],array['Mix the matzo meal with the egg and oil, chill for 20 minutes, then roll into small balls.','Simmer the stock with the carrot, onion and celery for 15 minutes.','Poach the matzo balls for 20 minutes, add the shredded chicken and noodles and finish with dill.']::text[],array['comfort','high protein']::text[],null),
(pg_temp.sid('recipe:Beef gyros with tzatziki'),'Beef gyros with tzatziki','dinner','Spiced sliced beef in a warm pita with a yogurt-cucumber sauce.',30,508,55.0,42.5,13.9,array['130 g sirloin steak, cooked','60 g wholemeal pita','80 g Greek yogurt 0% fat','80 g cucumber','70 g tomato','30 g onion','20 g mixed salad leaves','1/2 tsp dried oregano','1 clove garlic','1 tsp lemon juice']::text[],array['Season the beef with oregano, garlic and lemon and sear, then slice thinly.','Stir grated cucumber and garlic into the yogurt.','Fill the pita with beef, tomato, onion, leaves and a generous spoon of tzatziki.']::text[],array['high protein','mediterranean']::text[],null),
(pg_temp.sid('recipe:Chicken pot pie with a light topping'),'Chicken pot pie with a light topping','dinner','A creamy chicken and veg filling under a thin flaky-style crust.',45,677,61.3,71.8,15.3,array['150 g chicken breast, cooked','60 g peas, frozen','60 g carrot','100 g potato, boiled','150 ml milk, semi-skimmed','35 g plain flour','8 g butter','40 g onion','1/2 tsp dried thyme','100 ml chicken stock']::text[],array['Make a quick sauce: melt the butter, stir in 20 g flour, then whisk in the milk and a splash of stock until thick.','Fold in the chicken, peas, carrot, potato and thyme and spoon into a dish.','Mix the remaining flour with a little water into a paste, pat out a thin lid, cover and bake at 200C for 25 minutes.']::text[],array['comfort','family']::text[],null),
(pg_temp.sid('recipe:Spinach, chicken and mozzarella calzone'),'Spinach, chicken and mozzarella calzone','dinner','A folded pizza pocket with a lean chicken and spinach filling.',35,744,61.5,82.3,17.0,array['150 g pizza dough, baked','50 g mozzarella','100 g chicken breast, cooked','50 g spinach','80 g chopped tomatoes, canned','40 g mixed salad leaves','1 clove garlic','1/2 tsp dried oregano']::text[],array['Roll the dough into a circle and spread half with tomato.','Top that half with chicken, spinach and mozzarella, fold over and seal the edge.','Bake at 220C for 18 to 20 minutes and serve with a side salad.']::text[],array['comfort','high protein']::text[],null),
(pg_temp.sid('recipe:Quinoa and chickpea burger'),'Quinoa and chickpea burger','dinner','Hearty vegetarian patties baked until crisp outside.',35,763,35.0,110.1,22.1,array['100 g quinoa, cooked','120 g chickpeas, cooked','50 g eggs, whole','25 g oats, dry','70 g wholemeal burger bun','50 g avocado','50 g tomato','20 g mixed salad leaves','1/2 tsp ground cumin','1 clove garlic','1 tbsp chopped parsley']::text[],array['Mash the chickpeas and mix with the quinoa, egg, oats and spices.','Shape into patties and bake at 200C for 20 minutes, turning once.','Serve in the bun with avocado, tomato and leaves.']::text[],array['vegetarian','high fibre']::text[],null),
(pg_temp.sid('recipe:Slow-braised beef ragu with pappardelle'),'Slow-braised beef ragu with pappardelle','dinner','Rich, slow-cooked lean beef sauce over wide pasta ribbons.',60,730,57.8,63.7,26.6,array['140 g braising beef, cooked lean','160 g pasta, cooked','150 g chopped tomatoes, canned','40 g carrot','50 g onion','10 g parmesan','5 g olive oil','50 ml red wine (optional)','2 cloves garlic','1 sprig rosemary','200 ml beef stock']::text[],array['Brown the beef, then soften the onion, carrot and garlic in the same pan.','Add the tomatoes, stock and rosemary, cover and simmer for 1.5 hours until it falls apart.','Shred the beef into the sauce and serve over pasta with parmesan.']::text[],array['comfort','meal prep']::text[],null),
(pg_temp.sid('recipe:Beef and cabbage roll soup'),'Beef and cabbage roll soup','dinner','All the cabbage roll flavour in one pot with rice and tomato.',40,495,42.3,58.9,10.1,array['130 g beef mince 5% fat, cooked','200 g cabbage','120 g white rice, cooked','150 g chopped tomatoes, canned','50 g onion','40 g carrot','300 ml beef stock','1 tsp paprika','1 bay leaf']::text[],array['Brown the beef with the onion and carrot.','Add the cabbage, tomatoes, stock and paprika and simmer for 20 minutes.','Stir in the cooked rice and heat through.']::text[],array['comfort','one pot']::text[],null),
(pg_temp.sid('recipe:Peanut noodles with chicken'),'Peanut noodles with chicken','dinner','Silky peanut-soy noodles with crunchy veg and shredded chicken.',20,650,55.6,61.4,20.5,array['180 g rice noodles, cooked','25 g peanut butter','15 g soy sauce','120 g chicken breast, cooked','50 g carrot','60 g cucumber','60 g edamame','1 tbsp lime juice','pinch of chilli flakes','1 clove garlic']::text[],array['Whisk the peanut butter, soy sauce, lime and garlic with a splash of warm water.','Toss with the noodles, chicken and edamame.','Top with carrot and cucumber ribbons and chilli.']::text[],array['quick','asian']::text[],null),
(pg_temp.sid('recipe:Street corn chicken rice bowl'),'Street corn chicken rice bowl','dinner','Charred corn, spiced chicken and a tangy yogurt-lime sauce over rice.',25,722,70.7,80.8,12.5,array['160 g chicken breast, cooked','150 g white rice, cooked','100 g sweetcorn','60 g black beans, cooked','20 g feta','50 g Greek yogurt 0% fat','50 g bell pepper','1/2 lime','1/2 tsp chilli powder','1 tbsp chopped coriander']::text[],array['Char the corn in a dry hot pan until blackened in spots.','Season and sear the chicken, then slice.','Build the bowl on rice with beans, pepper, chicken and corn and finish with crumbled feta and lime yogurt.']::text[],array['high protein','mexican']::text[],null),
(pg_temp.sid('recipe:BBQ pulled pork sandwich with pineapple slaw'),'BBQ pulled pork sandwich with pineapple slaw','dinner','Lean shredded pork in smoky BBQ sauce with a fruity crunchy slaw.',40,549,52.8,64.4,9.1,array['150 g pork tenderloin, cooked','34 g BBQ sauce','70 g wholemeal burger bun','80 g cabbage','60 g pineapple','40 g mango','40 g Greek yogurt 0% fat','1/2 tsp smoked paprika','1 tsp lime juice']::text[],array['Simmer or slow-cook the pork with BBQ sauce and paprika until it shreds easily.','Toss the cabbage, pineapple and mango with the yogurt and lime juice.','Pile the pork into the bun and top with the slaw.']::text[],array['high protein','bbq']::text[],null),
(pg_temp.sid('recipe:Light shrimp alfredo'),'Light shrimp alfredo','dinner','A creamy garlic sauce made with cream cheese and parmesan instead of heavy cream.',20,657,60.3,65.3,17.3,array['150 g prawns, cooked','180 g pasta, cooked','40 g light cream cheese','100 ml milk, semi-skimmed','15 g parmesan','40 g spinach','5 g olive oil','1 clove garlic','black pepper to taste','1/2 tsp lemon zest']::text[],array['Warm the milk with the cream cheese, garlic and parmesan until smooth.','Sear the prawns in the oil for 2 minutes.','Toss the pasta, prawns, spinach and sauce together.']::text[],array['quick','high protein']::text[],null),
(pg_temp.sid('recipe:Chicken caesar wrap'),'Chicken caesar wrap','dinner','A caesar wrap with a yogurt-based dressing.',10,654,62.3,68.1,14.0,array['62 g tortilla wrap','140 g chicken breast, cooked','50 g mixed salad leaves','12 g parmesan','50 g Greek yogurt 0% fat','60 g tomato','150 g potato, boiled','1 tsp lemon juice','1/2 clove garlic','1/2 tsp Dijon mustard']::text[],array['Stir the yogurt with lemon juice, garlic, mustard and half the parmesan.','Toss the leaves and chicken in the dressing.','Pile onto the wrap with tomato, roll up and serve with boiled potatoes.']::text[],array['quick','high protein']::text[],null),
(pg_temp.sid('recipe:Lemon parmesan chicken pasta'),'Lemon parmesan chicken pasta','dinner','Bright lemony pasta with seared chicken and a little parmesan.',25,719,66.8,65.5,19.8,array['150 g chicken breast, cooked','180 g pasta, cooked','15 g parmesan','50 g spinach','8 g olive oil','50 g peas, frozen','zest and juice of 1/2 lemon','1 clove garlic','black pepper to taste']::text[],array['Sear the chicken, rest, then slice.','Toss the hot pasta with oil, garlic, lemon zest, juice, peas and spinach until wilted.','Fold in the chicken and parmesan.']::text[],array['high protein','quick']::text[],null),
(pg_temp.sid('recipe:Beef lomo saltado'),'Beef lomo saltado','dinner','Peruvian-style beef and onion stir-fry with tomatoes, served over rice with a few fries.',25,703,53.6,74.2,20.3,array['150 g sirloin steak, cooked','80 g onion','100 g tomato','150 g white rice, cooked','100 g potato, boiled','15 g soy sauce','6 g olive oil','1 clove garlic','1 tbsp red wine vinegar','1 tbsp chopped coriander']::text[],array['Roast the potato wedges at 220C for 25 minutes.','Stir-fry the sliced beef in a very hot pan for 2 minutes, add the onion and tomato.','Splash in the soy sauce and vinegar, toss in the potatoes and serve on rice.']::text[],array['high protein','latin']::text[],null),
(pg_temp.sid('recipe:Tomato mozzarella pizza'),'Tomato mozzarella pizza','dinner','A thin homemade pizza with fresh mozzarella and rocket.',30,765,59.8,83.2,19.6,array['150 g pizza dough, baked','70 g mozzarella','80 g chopped tomatoes, canned','60 g tomato','30 g mixed salad leaves','80 g chicken breast, cooked','6 fresh basil leaves','1 clove garlic','1 tsp olive oil to drizzle']::text[],array['Stretch the dough thin and spread with the tomato, garlic and a pinch of salt.','Top with torn mozzarella and sliced tomato and bake at 240C for 10 to 12 minutes.','Scatter over the leaves, chicken and basil.']::text[],array['vegetarian','weekend']::text[],null),
(pg_temp.sid('recipe:Salmon rice bowl'),'Salmon rice bowl','dinner','Teriyaki-style salmon over rice with edamame, cucumber and avocado.',25,673,45.1,61.1,26.8,array['140 g salmon fillet, cooked','150 g white rice, cooked','70 g edamame','60 g cucumber','40 g avocado','12 g soy sauce','8 g honey','1 tsp rice vinegar','1 tsp sesame seeds','1 spring onion']::text[],array['Brush the salmon with soy sauce and honey and bake at 200C for 10 to 12 minutes.','Dress the cucumber with a splash of rice vinegar.','Flake the salmon over rice and top with edamame, cucumber, avocado and sesame.']::text[],array['omega-3','high protein']::text[],null),
(pg_temp.sid('recipe:Salmon tacos with crunchy slaw'),'Salmon tacos with crunchy slaw','dinner','Seared salmon in corn tortillas with a lime-yogurt cabbage slaw.',25,583,42.7,46.9,25.3,array['140 g salmon fillet, cooked','78 g corn tortilla','80 g cabbage','50 g Greek yogurt 0% fat','40 g avocado','30 g salsa','1/2 lime','1/2 tsp chilli powder','1 tbsp chopped coriander']::text[],array['Rub the salmon with chilli powder and sear or bake until just cooked, then flake.','Mix the cabbage with the yogurt and lime juice for the slaw.','Fill warm tortillas with salmon, slaw, avocado and salsa.']::text[],array['omega-3','mexican']::text[],null),
(pg_temp.sid('recipe:Mediterranean turkey meatball bowl'),'Mediterranean turkey meatball bowl','dinner','Herby turkey meatballs on couscous with cucumber, tomato and feta.',35,697,58.9,56.9,26.0,array['150 g turkey mince, cooked','160 g couscous, cooked','70 g cucumber','80 g tomato','25 g feta','40 g hummus','10 g breadcrumbs','25 g eggs, whole','1 tsp dried oregano','1 tbsp lemon juice','1 tbsp chopped parsley']::text[],array['Mix the turkey, breadcrumbs, egg and oregano, shape into balls and bake at 200C for 15 minutes.','Fluff the couscous with lemon juice and parsley.','Serve the meatballs on the couscous with cucumber, tomato, feta and a spoon of hummus.']::text[],array['high protein','mediterranean']::text[],null),
(pg_temp.sid('recipe:Creamy garlic and herb pasta'),'Creamy garlic and herb pasta','dinner','Light herb cream cheese sauce with cherry tomatoes and chicken.',20,657,62.2,66.8,14.6,array['180 g pasta, cooked','40 g light cream cheese','130 g chicken breast, cooked','100 g tomato','40 g spinach','10 g parmesan','60 ml milk, semi-skimmed','1 clove garlic','1 tsp mixed herbs','black pepper to taste']::text[],array['Warm the cream cheese with the milk, garlic and herbs until smooth.','Toss through the pasta, chicken and halved tomatoes.','Wilt in the spinach and finish with parmesan.']::text[],array['quick','comfort']::text[],null),
(pg_temp.sid('recipe:Beef cevapi with pita and yogurt'),'Beef cevapi with pita and yogurt','dinner','Grilled spiced minced-beef rolls served in pita with onion and yogurt.',30,508,54.3,45.9,12.8,array['150 g beef mince 5% fat, cooked','60 g wholemeal pita','50 g onion','70 g Greek yogurt 0% fat','70 g tomato','60 g bell pepper','50 g cucumber','1 clove garlic','1 tsp paprika','pinch of bicarbonate of soda']::text[],array['Mix the mince with garlic, paprika and a splash of water, shape into short finger-sized rolls.','Grill or pan-fry for 8 to 10 minutes, turning until browned.','Serve in the pita with onion, tomato, pepper, cucumber and yogurt.']::text[],array['high protein','balkan']::text[],null),
(pg_temp.sid('recipe:Chicken panang curry'),'Chicken panang curry','dinner','A rich peanutty panang-style curry that stays light on calories.',30,698,60.1,60.4,23.5,array['160 g chicken breast, cooked','150 g light coconut milk','20 g curry paste','12 g peanut butter','80 g bell pepper','60 g green beans','150 g white rice, cooked','1 tbsp lime juice','1 tsp fish sauce','6 basil leaves']::text[],array['Fry the curry paste with the peanut butter for a minute.','Add the coconut milk, chicken, pepper and beans and simmer for 12 minutes.','Finish with basil and lime and serve over rice.']::text[],array['high protein','asian']::text[],null),
(pg_temp.sid('recipe:Baked sweet and sour chicken'),'Baked sweet and sour chicken','dinner','Crisp-baked chicken in a pineapple and pepper sweet-sour sauce.',30,617,59.0,76.4,7.0,array['170 g chicken breast, cooked','100 g pineapple','100 g bell pepper','40 g onion','150 g white rice, cooked','20 g tomato ketchup','8 g honey','1 tbsp rice vinegar','1 tbsp soy sauce','1 clove garlic']::text[],array['Bake the cubed chicken at 220C for 15 minutes until golden.','Simmer the ketchup, honey, vinegar, soy sauce and garlic with the peppers, onion and pineapple.','Toss the chicken through the sauce and serve on rice.']::text[],array['high protein','asian']::text[],null),
(pg_temp.sid('recipe:Lean ground beef tacos'),'Lean ground beef tacos','dinner','Weeknight tacos with lean beef, crisp lettuce and tomato.',20,623,57.0,57.3,19.4,array['140 g beef mince 5% fat, cooked','78 g corn tortilla','70 g tomato','30 g mixed salad leaves','20 g cheddar cheese','40 g salsa','40 g Greek yogurt 0% fat','60 g black beans, cooked','2 tsp taco seasoning','1/2 lime']::text[],array['Brown the beef with taco seasoning and a splash of water.','Warm the tortillas and the beans.','Fill with beef, beans, leaves, tomato, cheese, salsa and yogurt.']::text[],array['high protein','mexican']::text[],null),
(pg_temp.sid('recipe:Smoky black bean burger'),'Smoky black bean burger','dinner','A firm homemade black bean patty on a wholemeal bun.',30,799,37.2,125.8,18.5,array['150 g black beans, cooked','30 g oats, dry','50 g eggs, whole','70 g wholemeal burger bun','50 g avocado','50 g tomato','150 g sweet potato, baked','20 g mixed salad leaves','1/2 tsp smoked paprika','1/2 tsp ground cumin','1 clove garlic']::text[],array['Mash the beans with the oats, egg and spices and shape into a patty.','Pan-fry or bake for 6 minutes per side.','Serve in the bun with avocado, tomato, leaves and baked sweet potato.']::text[],array['vegetarian','high fibre']::text[],null),
(pg_temp.sid('recipe:Thai basil chicken with rice'),'Thai basil chicken with rice','dinner','Punchy minced chicken stir-fry with green beans, chilli and basil.',20,653,63.3,56.5,17.4,array['160 g chicken breast, cooked','100 g green beans','60 g bell pepper','160 g white rice, cooked','50 g eggs, whole','12 g soy sauce','6 g olive oil','1 tbsp fresh basil','1 clove garlic','1 red chilli','1 tsp fish sauce']::text[],array['Stir-fry the minced chicken in the oil until browned, then add garlic, chilli, beans and pepper.','Add the soy and fish sauce and toss until glossy, then stir in the basil.','Serve over rice topped with a fried egg.']::text[],array['quick','high protein']::text[],null),
(pg_temp.sid('recipe:Lighter Swedish meatballs'),'Lighter Swedish meatballs','dinner','Tender beef meatballs in a creamy mushroom gravy with potatoes.',35,623,56.1,65.8,15.3,array['140 g beef mince 5% fat, cooked','15 g breadcrumbs','25 g eggs, whole','80 g mushrooms','100 ml milk, semi-skimmed','40 g Greek yogurt 0% fat','200 g potato, boiled','8 g plain flour','100 ml beef stock','1/4 tsp ground allspice','1 tbsp fresh dill']::text[],array['Mix the beef, breadcrumbs, egg and allspice, shape into balls and bake at 200C for 15 minutes.','Fry the mushrooms, stir in the flour, then whisk in the milk and stock until thick; finish with yogurt.','Add the meatballs to the gravy and serve with boiled potatoes and dill.']::text[],array['comfort','high protein']::text[],null)
on conflict (id) do nothing;


insert into public.meal_plan_templates (id, name, goal, kcal, description, image_url, plan_no) values
(pg_temp.sid('mpt:tbfs-215'),'Taco Night and Takeaway Lite','Balanced',2000,'Carne asada tacos, a lighter General Tso''s, creamy tortellini soup, ham fried rice and honey mustard chicken.',null,215),
(pg_temp.sid('mpt:tbfs-214'),'Summer Grill Week','Muscle gain',2500,'Tostadas, a southwest pasta salad, cajun kebabs, turkey meatballs arrabbiata and smash burgers.',null,214),
(pg_temp.sid('mpt:tbfs-213'),'Comfort and Spice Week','Balanced',2200,'Walking taco bowls, creamy chicken and gnocchi, a veggie wrap, chicken red curry and kung pao.',null,213),
(pg_temp.sid('mpt:tbfs-212'),'Bowls and Cosy Soup Week','Fat loss',1700,'A quinoa nourish bowl, mushroom tacos, turkey sloppy joes, chicken dumpling soup and Thai chicken meatballs.',null,212),
(pg_temp.sid('mpt:tbfs-211'),'Wraps and Warm Bowls','Balanced',2000,'Green chile burritos, a chicken avocado wrap, loaded taco salad, matzo ball soup and beef gyros.',null,211),
(pg_temp.sid('mpt:tbfs-210'),'Autumn Comfort Week','Muscle gain',2600,'Chicken pot pie, calzone, quinoa burgers, slow-braised beef ragu and beef cabbage roll soup.',null,210),
(pg_temp.sid('mpt:tbfs-209'),'Quick Noodles and Sandwiches','Fat loss',1800,'Peanut noodles, a street corn chicken bowl, BBQ pulled pork, light shrimp alfredo and a chicken caesar wrap.',null,209),
(pg_temp.sid('mpt:tbfs-208'),'Italian and Island Week','Balanced',2100,'Lemon chicken pasta, lomo saltado, tomato mozzarella pizza, salmon rice bowls and BBQ pulled pork.',null,208),
(pg_temp.sid('mpt:tbfs-207'),'Fish, Meatballs and Curry Week','Fat loss',1800,'Salmon tacos, a Mediterranean meatball bowl, creamy herb pasta, beef cevapi and panang curry.',null,207),
(pg_temp.sid('mpt:tbfs-206'),'Takeout Classics, Lightened','Muscle gain',2400,'Sweet and sour chicken, beef tacos, black bean burgers, Thai basil chicken and Swedish meatballs.',null,206)
on conflict (id) do nothing;

insert into public.meal_plan_template_items (id, template_id, day, meal_type, recipe_id, servings, sort) values
(pg_temp.sid('mpti:215:1:breakfast'),pg_temp.sid('mpt:tbfs-215'),1,'breakfast',pg_temp.sid('recipe:Protein overnight oats'),1.0,0),
(pg_temp.sid('mpti:215:1:lunch'),pg_temp.sid('mpt:tbfs-215'),1,'lunch',pg_temp.sid('recipe:Chicken burrito bowl'),1.0,1),
(pg_temp.sid('mpti:215:1:dinner'),pg_temp.sid('mpt:tbfs-215'),1,'dinner',pg_temp.sid('recipe:Lean carne asada tacos'),1.0,2),
(pg_temp.sid('mpti:215:1:snack'),pg_temp.sid('mpt:tbfs-215'),1,'snack',pg_temp.sid('recipe:Cottage cheese and pineapple'),1.0,3),
(pg_temp.sid('mpti:215:2:breakfast'),pg_temp.sid('mpt:tbfs-215'),2,'breakfast',pg_temp.sid('recipe:Greek yogurt power bowl'),1.0,0),
(pg_temp.sid('mpti:215:2:lunch'),pg_temp.sid('mpt:tbfs-215'),2,'lunch',pg_temp.sid('recipe:Tuna and chickpea salad'),1.0,1),
(pg_temp.sid('mpti:215:2:dinner'),pg_temp.sid('mpt:tbfs-215'),2,'dinner',pg_temp.sid('recipe:Lighter General Tso''s chicken'),1.0,2),
(pg_temp.sid('mpti:215:2:snack'),pg_temp.sid('mpt:tbfs-215'),2,'snack',pg_temp.sid('recipe:Protein shake and banana'),1.0,3),
(pg_temp.sid('mpti:215:3:breakfast'),pg_temp.sid('mpt:tbfs-215'),3,'breakfast',pg_temp.sid('recipe:Veggie egg-white omelette'),1.3,0),
(pg_temp.sid('mpti:215:3:lunch'),pg_temp.sid('mpt:tbfs-215'),3,'lunch',pg_temp.sid('recipe:Turkey and hummus wrap'),1.3,1),
(pg_temp.sid('mpti:215:3:dinner'),pg_temp.sid('mpt:tbfs-215'),3,'dinner',pg_temp.sid('recipe:Creamy tomato tortellini soup'),1.3,2),
(pg_temp.sid('mpti:215:3:snack'),pg_temp.sid('mpt:tbfs-215'),3,'snack',pg_temp.sid('recipe:Skyr with berries and almonds'),1.3,3),
(pg_temp.sid('mpti:215:4:breakfast'),pg_temp.sid('mpt:tbfs-215'),4,'breakfast',pg_temp.sid('recipe:Banana protein pancakes'),1.0,0),
(pg_temp.sid('mpti:215:4:lunch'),pg_temp.sid('mpt:tbfs-215'),4,'lunch',pg_temp.sid('recipe:Quinoa and halloumi salad'),1.0,1),
(pg_temp.sid('mpti:215:4:dinner'),pg_temp.sid('mpt:tbfs-215'),4,'dinner',pg_temp.sid('recipe:Ham and egg fried rice'),1.0,2),
(pg_temp.sid('mpti:215:4:snack'),pg_temp.sid('mpt:tbfs-215'),4,'snack',pg_temp.sid('recipe:Boiled eggs and edamame'),1.0,3),
(pg_temp.sid('mpti:215:5:breakfast'),pg_temp.sid('mpt:tbfs-215'),5,'breakfast',pg_temp.sid('recipe:Smoked salmon bagel'),1.2,0),
(pg_temp.sid('mpti:215:5:lunch'),pg_temp.sid('mpt:tbfs-215'),5,'lunch',pg_temp.sid('recipe:Prawn noodle stir-fry'),1.2,1),
(pg_temp.sid('mpti:215:5:dinner'),pg_temp.sid('mpt:tbfs-215'),5,'dinner',pg_temp.sid('recipe:Honey mustard chicken with potatoes'),1.2,2),
(pg_temp.sid('mpti:215:5:snack'),pg_temp.sid('mpt:tbfs-215'),5,'snack',pg_temp.sid('recipe:Cottage cheese and pineapple'),1.2,3),
(pg_temp.sid('mpti:215:6:breakfast'),pg_temp.sid('mpt:tbfs-215'),6,'breakfast',pg_temp.sid('recipe:Scrambled eggs on sourdough'),1.1,0),
(pg_temp.sid('mpti:215:6:lunch'),pg_temp.sid('mpt:tbfs-215'),6,'lunch',pg_temp.sid('recipe:Lentil and vegetable soup'),1.1,1),
(pg_temp.sid('mpti:215:6:dinner'),pg_temp.sid('mpt:tbfs-215'),6,'dinner',pg_temp.sid('recipe:Lean carne asada tacos'),1.1,2),
(pg_temp.sid('mpti:215:6:snack'),pg_temp.sid('mpt:tbfs-215'),6,'snack',pg_temp.sid('recipe:Protein shake and banana'),1.1,3),
(pg_temp.sid('mpti:215:7:breakfast'),pg_temp.sid('mpt:tbfs-215'),7,'breakfast',pg_temp.sid('recipe:Protein overnight oats'),1.0,0),
(pg_temp.sid('mpti:215:7:lunch'),pg_temp.sid('mpt:tbfs-215'),7,'lunch',pg_temp.sid('recipe:Chicken burrito bowl'),1.0,1),
(pg_temp.sid('mpti:215:7:dinner'),pg_temp.sid('mpt:tbfs-215'),7,'dinner',pg_temp.sid('recipe:Creamy tomato tortellini soup'),1.0,2),
(pg_temp.sid('mpti:215:7:snack'),pg_temp.sid('mpt:tbfs-215'),7,'snack',pg_temp.sid('recipe:Skyr with berries and almonds'),1.0,3),
(pg_temp.sid('mpti:214:1:breakfast'),pg_temp.sid('mpt:tbfs-214'),1,'breakfast',pg_temp.sid('recipe:Greek yogurt power bowl'),1.4,0),
(pg_temp.sid('mpti:214:1:lunch'),pg_temp.sid('mpt:tbfs-214'),1,'lunch',pg_temp.sid('recipe:Tuna and chickpea salad'),1.4,1),
(pg_temp.sid('mpti:214:1:dinner'),pg_temp.sid('mpt:tbfs-214'),1,'dinner',pg_temp.sid('recipe:Black bean and beef tostadas'),1.4,2),
(pg_temp.sid('mpti:214:1:snack'),pg_temp.sid('mpt:tbfs-214'),1,'snack',pg_temp.sid('recipe:Apple and peanut butter'),1.4,3),
(pg_temp.sid('mpti:214:2:breakfast'),pg_temp.sid('mpt:tbfs-214'),2,'breakfast',pg_temp.sid('recipe:Veggie egg-white omelette'),1.5,0),
(pg_temp.sid('mpti:214:2:lunch'),pg_temp.sid('mpt:tbfs-214'),2,'lunch',pg_temp.sid('recipe:Turkey and hummus wrap'),1.5,1),
(pg_temp.sid('mpti:214:2:dinner'),pg_temp.sid('mpt:tbfs-214'),2,'dinner',pg_temp.sid('recipe:Southwest tortellini pasta salad'),1.5,2),
(pg_temp.sid('mpti:214:2:snack'),pg_temp.sid('mpt:tbfs-214'),2,'snack',pg_temp.sid('recipe:Rice cakes with almond butter'),1.5,3),
(pg_temp.sid('mpti:214:3:breakfast'),pg_temp.sid('mpt:tbfs-214'),3,'breakfast',pg_temp.sid('recipe:Banana protein pancakes'),1.4,0),
(pg_temp.sid('mpti:214:3:lunch'),pg_temp.sid('mpt:tbfs-214'),3,'lunch',pg_temp.sid('recipe:Quinoa and halloumi salad'),1.4,1),
(pg_temp.sid('mpti:214:3:dinner'),pg_temp.sid('mpt:tbfs-214'),3,'dinner',pg_temp.sid('recipe:Cajun chicken and sausage kebabs'),1.4,2),
(pg_temp.sid('mpti:214:3:snack'),pg_temp.sid('mpt:tbfs-214'),3,'snack',pg_temp.sid('recipe:Hummus and veg sticks'),1.4,3),
(pg_temp.sid('mpti:214:4:breakfast'),pg_temp.sid('mpt:tbfs-214'),4,'breakfast',pg_temp.sid('recipe:Smoked salmon bagel'),1.3,0),
(pg_temp.sid('mpti:214:4:lunch'),pg_temp.sid('mpt:tbfs-214'),4,'lunch',pg_temp.sid('recipe:Prawn noodle stir-fry'),1.3,1),
(pg_temp.sid('mpti:214:4:dinner'),pg_temp.sid('mpt:tbfs-214'),4,'dinner',pg_temp.sid('recipe:Turkey meatballs arrabbiata'),1.3,2),
(pg_temp.sid('mpti:214:4:snack'),pg_temp.sid('mpt:tbfs-214'),4,'snack',pg_temp.sid('recipe:Dark chocolate and almonds'),1.3,3),
(pg_temp.sid('mpti:214:5:breakfast'),pg_temp.sid('mpt:tbfs-214'),5,'breakfast',pg_temp.sid('recipe:Scrambled eggs on sourdough'),1.4,0),
(pg_temp.sid('mpti:214:5:lunch'),pg_temp.sid('mpt:tbfs-214'),5,'lunch',pg_temp.sid('recipe:Lentil and vegetable soup'),1.4,1),
(pg_temp.sid('mpti:214:5:dinner'),pg_temp.sid('mpt:tbfs-214'),5,'dinner',pg_temp.sid('recipe:Smash burger with tomato and lettuce'),1.4,2),
(pg_temp.sid('mpti:214:5:snack'),pg_temp.sid('mpt:tbfs-214'),5,'snack',pg_temp.sid('recipe:Apple and peanut butter'),1.4,3),
(pg_temp.sid('mpti:214:6:breakfast'),pg_temp.sid('mpt:tbfs-214'),6,'breakfast',pg_temp.sid('recipe:Protein overnight oats'),1.2,0),
(pg_temp.sid('mpti:214:6:lunch'),pg_temp.sid('mpt:tbfs-214'),6,'lunch',pg_temp.sid('recipe:Chicken burrito bowl'),1.2,1),
(pg_temp.sid('mpti:214:6:dinner'),pg_temp.sid('mpt:tbfs-214'),6,'dinner',pg_temp.sid('recipe:Black bean and beef tostadas'),1.2,2),
(pg_temp.sid('mpti:214:6:snack'),pg_temp.sid('mpt:tbfs-214'),6,'snack',pg_temp.sid('recipe:Rice cakes with almond butter'),1.2,3),
(pg_temp.sid('mpti:214:7:breakfast'),pg_temp.sid('mpt:tbfs-214'),7,'breakfast',pg_temp.sid('recipe:Greek yogurt power bowl'),1.4,0),
(pg_temp.sid('mpti:214:7:lunch'),pg_temp.sid('mpt:tbfs-214'),7,'lunch',pg_temp.sid('recipe:Tuna and chickpea salad'),1.4,1),
(pg_temp.sid('mpti:214:7:dinner'),pg_temp.sid('mpt:tbfs-214'),7,'dinner',pg_temp.sid('recipe:Cajun chicken and sausage kebabs'),1.4,2),
(pg_temp.sid('mpti:214:7:snack'),pg_temp.sid('mpt:tbfs-214'),7,'snack',pg_temp.sid('recipe:Hummus and veg sticks'),1.4,3),
(pg_temp.sid('mpti:213:1:breakfast'),pg_temp.sid('mpt:tbfs-213'),1,'breakfast',pg_temp.sid('recipe:Veggie egg-white omelette'),1.2,0),
(pg_temp.sid('mpti:213:1:lunch'),pg_temp.sid('mpt:tbfs-213'),1,'lunch',pg_temp.sid('recipe:Turkey and hummus wrap'),1.2,1),
(pg_temp.sid('mpti:213:1:dinner'),pg_temp.sid('mpt:tbfs-213'),1,'dinner',pg_temp.sid('recipe:Walking taco bowl'),1.2,2),
(pg_temp.sid('mpti:213:1:snack'),pg_temp.sid('mpt:tbfs-213'),1,'snack',pg_temp.sid('recipe:Protein shake and banana'),1.2,3),
(pg_temp.sid('mpti:213:2:breakfast'),pg_temp.sid('mpt:tbfs-213'),2,'breakfast',pg_temp.sid('recipe:Banana protein pancakes'),1.2,0),
(pg_temp.sid('mpti:213:2:lunch'),pg_temp.sid('mpt:tbfs-213'),2,'lunch',pg_temp.sid('recipe:Quinoa and halloumi salad'),1.2,1),
(pg_temp.sid('mpti:213:2:dinner'),pg_temp.sid('mpt:tbfs-213'),2,'dinner',pg_temp.sid('recipe:Creamy chicken and gnocchi'),1.2,2),
(pg_temp.sid('mpti:213:2:snack'),pg_temp.sid('mpt:tbfs-213'),2,'snack',pg_temp.sid('recipe:Skyr with berries and almonds'),1.2,3),
(pg_temp.sid('mpti:213:3:breakfast'),pg_temp.sid('mpt:tbfs-213'),3,'breakfast',pg_temp.sid('recipe:Smoked salmon bagel'),1.2,0),
(pg_temp.sid('mpti:213:3:lunch'),pg_temp.sid('mpt:tbfs-213'),3,'lunch',pg_temp.sid('recipe:Prawn noodle stir-fry'),1.2,1),
(pg_temp.sid('mpti:213:3:dinner'),pg_temp.sid('mpt:tbfs-213'),3,'dinner',pg_temp.sid('recipe:Hummus and edamame veggie wrap'),1.2,2),
(pg_temp.sid('mpti:213:3:snack'),pg_temp.sid('mpt:tbfs-213'),3,'snack',pg_temp.sid('recipe:Boiled eggs and edamame'),1.2,3),
(pg_temp.sid('mpti:213:4:breakfast'),pg_temp.sid('mpt:tbfs-213'),4,'breakfast',pg_temp.sid('recipe:Scrambled eggs on sourdough'),1.2,0),
(pg_temp.sid('mpti:213:4:lunch'),pg_temp.sid('mpt:tbfs-213'),4,'lunch',pg_temp.sid('recipe:Lentil and vegetable soup'),1.2,1),
(pg_temp.sid('mpti:213:4:dinner'),pg_temp.sid('mpt:tbfs-213'),4,'dinner',pg_temp.sid('recipe:Chicken red curry'),1.2,2),
(pg_temp.sid('mpti:213:4:snack'),pg_temp.sid('mpt:tbfs-213'),4,'snack',pg_temp.sid('recipe:Cottage cheese and pineapple'),1.2,3),
(pg_temp.sid('mpti:213:5:breakfast'),pg_temp.sid('mpt:tbfs-213'),5,'breakfast',pg_temp.sid('recipe:Protein overnight oats'),0.9,0),
(pg_temp.sid('mpti:213:5:lunch'),pg_temp.sid('mpt:tbfs-213'),5,'lunch',pg_temp.sid('recipe:Chicken burrito bowl'),0.9,1),
(pg_temp.sid('mpti:213:5:dinner'),pg_temp.sid('mpt:tbfs-213'),5,'dinner',pg_temp.sid('recipe:Kung pao chicken'),0.9,2),
(pg_temp.sid('mpti:213:5:snack'),pg_temp.sid('mpt:tbfs-213'),5,'snack',pg_temp.sid('recipe:Protein shake and banana'),0.9,3),
(pg_temp.sid('mpti:213:6:breakfast'),pg_temp.sid('mpt:tbfs-213'),6,'breakfast',pg_temp.sid('recipe:Greek yogurt power bowl'),1.2,0),
(pg_temp.sid('mpti:213:6:lunch'),pg_temp.sid('mpt:tbfs-213'),6,'lunch',pg_temp.sid('recipe:Tuna and chickpea salad'),1.2,1),
(pg_temp.sid('mpti:213:6:dinner'),pg_temp.sid('mpt:tbfs-213'),6,'dinner',pg_temp.sid('recipe:Walking taco bowl'),1.2,2),
(pg_temp.sid('mpti:213:6:snack'),pg_temp.sid('mpt:tbfs-213'),6,'snack',pg_temp.sid('recipe:Skyr with berries and almonds'),1.2,3),
(pg_temp.sid('mpti:213:7:breakfast'),pg_temp.sid('mpt:tbfs-213'),7,'breakfast',pg_temp.sid('recipe:Veggie egg-white omelette'),1.2,0),
(pg_temp.sid('mpti:213:7:lunch'),pg_temp.sid('mpt:tbfs-213'),7,'lunch',pg_temp.sid('recipe:Turkey and hummus wrap'),1.2,1),
(pg_temp.sid('mpti:213:7:dinner'),pg_temp.sid('mpt:tbfs-213'),7,'dinner',pg_temp.sid('recipe:Hummus and edamame veggie wrap'),1.2,2),
(pg_temp.sid('mpti:213:7:snack'),pg_temp.sid('mpt:tbfs-213'),7,'snack',pg_temp.sid('recipe:Boiled eggs and edamame'),1.2,3),
(pg_temp.sid('mpti:212:1:breakfast'),pg_temp.sid('mpt:tbfs-212'),1,'breakfast',pg_temp.sid('recipe:Banana protein pancakes'),0.9,0),
(pg_temp.sid('mpti:212:1:lunch'),pg_temp.sid('mpt:tbfs-212'),1,'lunch',pg_temp.sid('recipe:Quinoa and halloumi salad'),0.9,1),
(pg_temp.sid('mpti:212:1:dinner'),pg_temp.sid('mpt:tbfs-212'),1,'dinner',pg_temp.sid('recipe:Quinoa nourish bowl'),0.9,2),
(pg_temp.sid('mpti:212:1:snack'),pg_temp.sid('mpt:tbfs-212'),1,'snack',pg_temp.sid('recipe:Rice cakes with almond butter'),0.9,3),
(pg_temp.sid('mpti:212:2:breakfast'),pg_temp.sid('mpt:tbfs-212'),2,'breakfast',pg_temp.sid('recipe:Smoked salmon bagel'),1.0,0),
(pg_temp.sid('mpti:212:2:lunch'),pg_temp.sid('mpt:tbfs-212'),2,'lunch',pg_temp.sid('recipe:Prawn noodle stir-fry'),1.0,1),
(pg_temp.sid('mpti:212:2:dinner'),pg_temp.sid('mpt:tbfs-212'),2,'dinner',pg_temp.sid('recipe:Mushroom and black bean tacos'),1.0,2),
(pg_temp.sid('mpti:212:2:snack'),pg_temp.sid('mpt:tbfs-212'),2,'snack',pg_temp.sid('recipe:Hummus and veg sticks'),1.0,3),
(pg_temp.sid('mpti:212:3:breakfast'),pg_temp.sid('mpt:tbfs-212'),3,'breakfast',pg_temp.sid('recipe:Scrambled eggs on sourdough'),1.0,0),
(pg_temp.sid('mpti:212:3:lunch'),pg_temp.sid('mpt:tbfs-212'),3,'lunch',pg_temp.sid('recipe:Lentil and vegetable soup'),1.0,1),
(pg_temp.sid('mpti:212:3:dinner'),pg_temp.sid('mpt:tbfs-212'),3,'dinner',pg_temp.sid('recipe:Turkey sloppy joes'),1.0,2),
(pg_temp.sid('mpti:212:3:snack'),pg_temp.sid('mpt:tbfs-212'),3,'snack',pg_temp.sid('recipe:Dark chocolate and almonds'),1.0,3),
(pg_temp.sid('mpti:212:4:breakfast'),pg_temp.sid('mpt:tbfs-212'),4,'breakfast',pg_temp.sid('recipe:Protein overnight oats'),0.8,0),
(pg_temp.sid('mpti:212:4:lunch'),pg_temp.sid('mpt:tbfs-212'),4,'lunch',pg_temp.sid('recipe:Chicken burrito bowl'),0.8,1),
(pg_temp.sid('mpti:212:4:dinner'),pg_temp.sid('mpt:tbfs-212'),4,'dinner',pg_temp.sid('recipe:Chicken dumpling soup'),0.8,2),
(pg_temp.sid('mpti:212:4:snack'),pg_temp.sid('mpt:tbfs-212'),4,'snack',pg_temp.sid('recipe:Apple and peanut butter'),0.8,3),
(pg_temp.sid('mpti:212:5:breakfast'),pg_temp.sid('mpt:tbfs-212'),5,'breakfast',pg_temp.sid('recipe:Greek yogurt power bowl'),0.9,0),
(pg_temp.sid('mpti:212:5:lunch'),pg_temp.sid('mpt:tbfs-212'),5,'lunch',pg_temp.sid('recipe:Tuna and chickpea salad'),0.9,1),
(pg_temp.sid('mpti:212:5:dinner'),pg_temp.sid('mpt:tbfs-212'),5,'dinner',pg_temp.sid('recipe:Thai green curry chicken meatballs'),0.9,2),
(pg_temp.sid('mpti:212:5:snack'),pg_temp.sid('mpt:tbfs-212'),5,'snack',pg_temp.sid('recipe:Rice cakes with almond butter'),0.9,3),
(pg_temp.sid('mpti:212:6:breakfast'),pg_temp.sid('mpt:tbfs-212'),6,'breakfast',pg_temp.sid('recipe:Veggie egg-white omelette'),1.0,0),
(pg_temp.sid('mpti:212:6:lunch'),pg_temp.sid('mpt:tbfs-212'),6,'lunch',pg_temp.sid('recipe:Turkey and hummus wrap'),1.0,1),
(pg_temp.sid('mpti:212:6:dinner'),pg_temp.sid('mpt:tbfs-212'),6,'dinner',pg_temp.sid('recipe:Quinoa nourish bowl'),1.0,2),
(pg_temp.sid('mpti:212:6:snack'),pg_temp.sid('mpt:tbfs-212'),6,'snack',pg_temp.sid('recipe:Hummus and veg sticks'),1.0,3),
(pg_temp.sid('mpti:212:7:breakfast'),pg_temp.sid('mpt:tbfs-212'),7,'breakfast',pg_temp.sid('recipe:Banana protein pancakes'),0.9,0),
(pg_temp.sid('mpti:212:7:lunch'),pg_temp.sid('mpt:tbfs-212'),7,'lunch',pg_temp.sid('recipe:Quinoa and halloumi salad'),0.9,1),
(pg_temp.sid('mpti:212:7:dinner'),pg_temp.sid('mpt:tbfs-212'),7,'dinner',pg_temp.sid('recipe:Turkey sloppy joes'),0.9,2),
(pg_temp.sid('mpti:212:7:snack'),pg_temp.sid('mpt:tbfs-212'),7,'snack',pg_temp.sid('recipe:Dark chocolate and almonds'),0.9,3),
(pg_temp.sid('mpti:211:1:breakfast'),pg_temp.sid('mpt:tbfs-211'),1,'breakfast',pg_temp.sid('recipe:Smoked salmon bagel'),1.0,0),
(pg_temp.sid('mpti:211:1:lunch'),pg_temp.sid('mpt:tbfs-211'),1,'lunch',pg_temp.sid('recipe:Prawn noodle stir-fry'),1.0,1),
(pg_temp.sid('mpti:211:1:dinner'),pg_temp.sid('mpt:tbfs-211'),1,'dinner',pg_temp.sid('recipe:Green chile chicken burritos'),1.0,2),
(pg_temp.sid('mpti:211:1:snack'),pg_temp.sid('mpt:tbfs-211'),1,'snack',pg_temp.sid('recipe:Skyr with berries and almonds'),1.0,3),
(pg_temp.sid('mpti:211:2:breakfast'),pg_temp.sid('mpt:tbfs-211'),2,'breakfast',pg_temp.sid('recipe:Scrambled eggs on sourdough'),1.1,0),
(pg_temp.sid('mpti:211:2:lunch'),pg_temp.sid('mpt:tbfs-211'),2,'lunch',pg_temp.sid('recipe:Lentil and vegetable soup'),1.1,1),
(pg_temp.sid('mpti:211:2:dinner'),pg_temp.sid('mpt:tbfs-211'),2,'dinner',pg_temp.sid('recipe:Chicken, bacon and avocado wrap'),1.1,2),
(pg_temp.sid('mpti:211:2:snack'),pg_temp.sid('mpt:tbfs-211'),2,'snack',pg_temp.sid('recipe:Boiled eggs and edamame'),1.1,3),
(pg_temp.sid('mpti:211:3:breakfast'),pg_temp.sid('mpt:tbfs-211'),3,'breakfast',pg_temp.sid('recipe:Protein overnight oats'),1.0,0),
(pg_temp.sid('mpti:211:3:lunch'),pg_temp.sid('mpt:tbfs-211'),3,'lunch',pg_temp.sid('recipe:Chicken burrito bowl'),1.0,1),
(pg_temp.sid('mpti:211:3:dinner'),pg_temp.sid('mpt:tbfs-211'),3,'dinner',pg_temp.sid('recipe:Loaded taco salad'),1.0,2),
(pg_temp.sid('mpti:211:3:snack'),pg_temp.sid('mpt:tbfs-211'),3,'snack',pg_temp.sid('recipe:Cottage cheese and pineapple'),1.0,3),
(pg_temp.sid('mpti:211:4:breakfast'),pg_temp.sid('mpt:tbfs-211'),4,'breakfast',pg_temp.sid('recipe:Greek yogurt power bowl'),1.0,0),
(pg_temp.sid('mpti:211:4:lunch'),pg_temp.sid('mpt:tbfs-211'),4,'lunch',pg_temp.sid('recipe:Tuna and chickpea salad'),1.0,1),
(pg_temp.sid('mpti:211:4:dinner'),pg_temp.sid('mpt:tbfs-211'),4,'dinner',pg_temp.sid('recipe:Chicken and matzo ball soup'),1.0,2),
(pg_temp.sid('mpti:211:4:snack'),pg_temp.sid('mpt:tbfs-211'),4,'snack',pg_temp.sid('recipe:Protein shake and banana'),1.0,3),
(pg_temp.sid('mpti:211:5:breakfast'),pg_temp.sid('mpt:tbfs-211'),5,'breakfast',pg_temp.sid('recipe:Veggie egg-white omelette'),1.3,0),
(pg_temp.sid('mpti:211:5:lunch'),pg_temp.sid('mpt:tbfs-211'),5,'lunch',pg_temp.sid('recipe:Turkey and hummus wrap'),1.3,1),
(pg_temp.sid('mpti:211:5:dinner'),pg_temp.sid('mpt:tbfs-211'),5,'dinner',pg_temp.sid('recipe:Beef gyros with tzatziki'),1.3,2),
(pg_temp.sid('mpti:211:5:snack'),pg_temp.sid('mpt:tbfs-211'),5,'snack',pg_temp.sid('recipe:Skyr with berries and almonds'),1.3,3),
(pg_temp.sid('mpti:211:6:breakfast'),pg_temp.sid('mpt:tbfs-211'),6,'breakfast',pg_temp.sid('recipe:Banana protein pancakes'),1.0,0),
(pg_temp.sid('mpti:211:6:lunch'),pg_temp.sid('mpt:tbfs-211'),6,'lunch',pg_temp.sid('recipe:Quinoa and halloumi salad'),1.0,1),
(pg_temp.sid('mpti:211:6:dinner'),pg_temp.sid('mpt:tbfs-211'),6,'dinner',pg_temp.sid('recipe:Green chile chicken burritos'),1.0,2),
(pg_temp.sid('mpti:211:6:snack'),pg_temp.sid('mpt:tbfs-211'),6,'snack',pg_temp.sid('recipe:Boiled eggs and edamame'),1.0,3),
(pg_temp.sid('mpti:211:7:breakfast'),pg_temp.sid('mpt:tbfs-211'),7,'breakfast',pg_temp.sid('recipe:Smoked salmon bagel'),1.2,0),
(pg_temp.sid('mpti:211:7:lunch'),pg_temp.sid('mpt:tbfs-211'),7,'lunch',pg_temp.sid('recipe:Prawn noodle stir-fry'),1.2,1),
(pg_temp.sid('mpti:211:7:dinner'),pg_temp.sid('mpt:tbfs-211'),7,'dinner',pg_temp.sid('recipe:Loaded taco salad'),1.2,2),
(pg_temp.sid('mpti:211:7:snack'),pg_temp.sid('mpt:tbfs-211'),7,'snack',pg_temp.sid('recipe:Cottage cheese and pineapple'),1.2,3),
(pg_temp.sid('mpti:210:1:breakfast'),pg_temp.sid('mpt:tbfs-210'),1,'breakfast',pg_temp.sid('recipe:Scrambled eggs on sourdough'),1.5,0),
(pg_temp.sid('mpti:210:1:lunch'),pg_temp.sid('mpt:tbfs-210'),1,'lunch',pg_temp.sid('recipe:Lentil and vegetable soup'),1.5,1),
(pg_temp.sid('mpti:210:1:dinner'),pg_temp.sid('mpt:tbfs-210'),1,'dinner',pg_temp.sid('recipe:Chicken pot pie with a light topping'),1.5,2),
(pg_temp.sid('mpti:210:1:snack'),pg_temp.sid('mpt:tbfs-210'),1,'snack',pg_temp.sid('recipe:Hummus and veg sticks'),1.5,3),
(pg_temp.sid('mpti:210:2:breakfast'),pg_temp.sid('mpt:tbfs-210'),2,'breakfast',pg_temp.sid('recipe:Protein overnight oats'),1.2,0),
(pg_temp.sid('mpti:210:2:lunch'),pg_temp.sid('mpt:tbfs-210'),2,'lunch',pg_temp.sid('recipe:Chicken burrito bowl'),1.2,1),
(pg_temp.sid('mpti:210:2:dinner'),pg_temp.sid('mpt:tbfs-210'),2,'dinner',pg_temp.sid('recipe:Spinach, chicken and mozzarella calzone'),1.2,2),
(pg_temp.sid('mpti:210:2:snack'),pg_temp.sid('mpt:tbfs-210'),2,'snack',pg_temp.sid('recipe:Dark chocolate and almonds'),1.2,3),
(pg_temp.sid('mpti:210:3:breakfast'),pg_temp.sid('mpt:tbfs-210'),3,'breakfast',pg_temp.sid('recipe:Greek yogurt power bowl'),1.4,0),
(pg_temp.sid('mpti:210:3:lunch'),pg_temp.sid('mpt:tbfs-210'),3,'lunch',pg_temp.sid('recipe:Tuna and chickpea salad'),1.4,1),
(pg_temp.sid('mpti:210:3:dinner'),pg_temp.sid('mpt:tbfs-210'),3,'dinner',pg_temp.sid('recipe:Quinoa and chickpea burger'),1.4,2),
(pg_temp.sid('mpti:210:3:snack'),pg_temp.sid('mpt:tbfs-210'),3,'snack',pg_temp.sid('recipe:Apple and peanut butter'),1.4,3),
(pg_temp.sid('mpti:210:4:breakfast'),pg_temp.sid('mpt:tbfs-210'),4,'breakfast',pg_temp.sid('recipe:Veggie egg-white omelette'),1.5,0),
(pg_temp.sid('mpti:210:4:lunch'),pg_temp.sid('mpt:tbfs-210'),4,'lunch',pg_temp.sid('recipe:Turkey and hummus wrap'),1.5,1),
(pg_temp.sid('mpti:210:4:dinner'),pg_temp.sid('mpt:tbfs-210'),4,'dinner',pg_temp.sid('recipe:Slow-braised beef ragu with pappardelle'),1.5,2),
(pg_temp.sid('mpti:210:4:snack'),pg_temp.sid('mpt:tbfs-210'),4,'snack',pg_temp.sid('recipe:Rice cakes with almond butter'),1.5,3),
(pg_temp.sid('mpti:210:5:breakfast'),pg_temp.sid('mpt:tbfs-210'),5,'breakfast',pg_temp.sid('recipe:Banana protein pancakes'),1.6,0),
(pg_temp.sid('mpti:210:5:lunch'),pg_temp.sid('mpt:tbfs-210'),5,'lunch',pg_temp.sid('recipe:Quinoa and halloumi salad'),1.6,1),
(pg_temp.sid('mpti:210:5:dinner'),pg_temp.sid('mpt:tbfs-210'),5,'dinner',pg_temp.sid('recipe:Beef and cabbage roll soup'),1.6,2),
(pg_temp.sid('mpti:210:5:snack'),pg_temp.sid('mpt:tbfs-210'),5,'snack',pg_temp.sid('recipe:Hummus and veg sticks'),1.6,3),
(pg_temp.sid('mpti:210:6:breakfast'),pg_temp.sid('mpt:tbfs-210'),6,'breakfast',pg_temp.sid('recipe:Smoked salmon bagel'),1.4,0),
(pg_temp.sid('mpti:210:6:lunch'),pg_temp.sid('mpt:tbfs-210'),6,'lunch',pg_temp.sid('recipe:Prawn noodle stir-fry'),1.4,1),
(pg_temp.sid('mpti:210:6:dinner'),pg_temp.sid('mpt:tbfs-210'),6,'dinner',pg_temp.sid('recipe:Chicken pot pie with a light topping'),1.4,2),
(pg_temp.sid('mpti:210:6:snack'),pg_temp.sid('mpt:tbfs-210'),6,'snack',pg_temp.sid('recipe:Dark chocolate and almonds'),1.4,3),
(pg_temp.sid('mpti:210:7:breakfast'),pg_temp.sid('mpt:tbfs-210'),7,'breakfast',pg_temp.sid('recipe:Scrambled eggs on sourdough'),1.4,0),
(pg_temp.sid('mpti:210:7:lunch'),pg_temp.sid('mpt:tbfs-210'),7,'lunch',pg_temp.sid('recipe:Lentil and vegetable soup'),1.4,1),
(pg_temp.sid('mpti:210:7:dinner'),pg_temp.sid('mpt:tbfs-210'),7,'dinner',pg_temp.sid('recipe:Quinoa and chickpea burger'),1.4,2),
(pg_temp.sid('mpti:210:7:snack'),pg_temp.sid('mpt:tbfs-210'),7,'snack',pg_temp.sid('recipe:Apple and peanut butter'),1.4,3),
(pg_temp.sid('mpti:209:1:breakfast'),pg_temp.sid('mpt:tbfs-209'),1,'breakfast',pg_temp.sid('recipe:Protein overnight oats'),0.8,0),
(pg_temp.sid('mpti:209:1:lunch'),pg_temp.sid('mpt:tbfs-209'),1,'lunch',pg_temp.sid('recipe:Chicken burrito bowl'),0.8,1),
(pg_temp.sid('mpti:209:1:dinner'),pg_temp.sid('mpt:tbfs-209'),1,'dinner',pg_temp.sid('recipe:Peanut noodles with chicken'),0.8,2),
(pg_temp.sid('mpti:209:1:snack'),pg_temp.sid('mpt:tbfs-209'),1,'snack',pg_temp.sid('recipe:Boiled eggs and edamame'),0.8,3),
(pg_temp.sid('mpti:209:2:breakfast'),pg_temp.sid('mpt:tbfs-209'),2,'breakfast',pg_temp.sid('recipe:Greek yogurt power bowl'),1.0,0),
(pg_temp.sid('mpti:209:2:lunch'),pg_temp.sid('mpt:tbfs-209'),2,'lunch',pg_temp.sid('recipe:Tuna and chickpea salad'),1.0,1),
(pg_temp.sid('mpti:209:2:dinner'),pg_temp.sid('mpt:tbfs-209'),2,'dinner',pg_temp.sid('recipe:Street corn chicken rice bowl'),1.0,2),
(pg_temp.sid('mpti:209:2:snack'),pg_temp.sid('mpt:tbfs-209'),2,'snack',pg_temp.sid('recipe:Cottage cheese and pineapple'),1.0,3),
(pg_temp.sid('mpti:209:3:breakfast'),pg_temp.sid('mpt:tbfs-209'),3,'breakfast',pg_temp.sid('recipe:Veggie egg-white omelette'),1.1,0),
(pg_temp.sid('mpti:209:3:lunch'),pg_temp.sid('mpt:tbfs-209'),3,'lunch',pg_temp.sid('recipe:Turkey and hummus wrap'),1.1,1),
(pg_temp.sid('mpti:209:3:dinner'),pg_temp.sid('mpt:tbfs-209'),3,'dinner',pg_temp.sid('recipe:BBQ pulled pork sandwich with pineapple slaw'),1.1,2),
(pg_temp.sid('mpti:209:3:snack'),pg_temp.sid('mpt:tbfs-209'),3,'snack',pg_temp.sid('recipe:Protein shake and banana'),1.1,3),
(pg_temp.sid('mpti:209:4:breakfast'),pg_temp.sid('mpt:tbfs-209'),4,'breakfast',pg_temp.sid('recipe:Banana protein pancakes'),1.0,0),
(pg_temp.sid('mpti:209:4:lunch'),pg_temp.sid('mpt:tbfs-209'),4,'lunch',pg_temp.sid('recipe:Quinoa and halloumi salad'),1.0,1),
(pg_temp.sid('mpti:209:4:dinner'),pg_temp.sid('mpt:tbfs-209'),4,'dinner',pg_temp.sid('recipe:Light shrimp alfredo'),1.0,2),
(pg_temp.sid('mpti:209:4:snack'),pg_temp.sid('mpt:tbfs-209'),4,'snack',pg_temp.sid('recipe:Skyr with berries and almonds'),1.0,3),
(pg_temp.sid('mpti:209:5:breakfast'),pg_temp.sid('mpt:tbfs-209'),5,'breakfast',pg_temp.sid('recipe:Smoked salmon bagel'),1.0,0),
(pg_temp.sid('mpti:209:5:lunch'),pg_temp.sid('mpt:tbfs-209'),5,'lunch',pg_temp.sid('recipe:Prawn noodle stir-fry'),1.0,1),
(pg_temp.sid('mpti:209:5:dinner'),pg_temp.sid('mpt:tbfs-209'),5,'dinner',pg_temp.sid('recipe:Chicken caesar wrap'),1.0,2),
(pg_temp.sid('mpti:209:5:snack'),pg_temp.sid('mpt:tbfs-209'),5,'snack',pg_temp.sid('recipe:Boiled eggs and edamame'),1.0,3),
(pg_temp.sid('mpti:209:6:breakfast'),pg_temp.sid('mpt:tbfs-209'),6,'breakfast',pg_temp.sid('recipe:Scrambled eggs on sourdough'),1.0,0),
(pg_temp.sid('mpti:209:6:lunch'),pg_temp.sid('mpt:tbfs-209'),6,'lunch',pg_temp.sid('recipe:Lentil and vegetable soup'),1.0,1),
(pg_temp.sid('mpti:209:6:dinner'),pg_temp.sid('mpt:tbfs-209'),6,'dinner',pg_temp.sid('recipe:Peanut noodles with chicken'),1.0,2),
(pg_temp.sid('mpti:209:6:snack'),pg_temp.sid('mpt:tbfs-209'),6,'snack',pg_temp.sid('recipe:Cottage cheese and pineapple'),1.0,3),
(pg_temp.sid('mpti:209:7:breakfast'),pg_temp.sid('mpt:tbfs-209'),7,'breakfast',pg_temp.sid('recipe:Protein overnight oats'),0.8,0),
(pg_temp.sid('mpti:209:7:lunch'),pg_temp.sid('mpt:tbfs-209'),7,'lunch',pg_temp.sid('recipe:Chicken burrito bowl'),0.8,1),
(pg_temp.sid('mpti:209:7:dinner'),pg_temp.sid('mpt:tbfs-209'),7,'dinner',pg_temp.sid('recipe:BBQ pulled pork sandwich with pineapple slaw'),0.8,2),
(pg_temp.sid('mpti:209:7:snack'),pg_temp.sid('mpt:tbfs-209'),7,'snack',pg_temp.sid('recipe:Protein shake and banana'),0.8,3),
(pg_temp.sid('mpti:208:1:breakfast'),pg_temp.sid('mpt:tbfs-208'),1,'breakfast',pg_temp.sid('recipe:Greek yogurt power bowl'),1.1,0),
(pg_temp.sid('mpti:208:1:lunch'),pg_temp.sid('mpt:tbfs-208'),1,'lunch',pg_temp.sid('recipe:Tuna and chickpea salad'),1.1,1),
(pg_temp.sid('mpti:208:1:dinner'),pg_temp.sid('mpt:tbfs-208'),1,'dinner',pg_temp.sid('recipe:Lemon parmesan chicken pasta'),1.1,2),
(pg_temp.sid('mpti:208:1:snack'),pg_temp.sid('mpt:tbfs-208'),1,'snack',pg_temp.sid('recipe:Dark chocolate and almonds'),1.1,3),
(pg_temp.sid('mpti:208:2:breakfast'),pg_temp.sid('mpt:tbfs-208'),2,'breakfast',pg_temp.sid('recipe:Veggie egg-white omelette'),1.2,0),
(pg_temp.sid('mpti:208:2:lunch'),pg_temp.sid('mpt:tbfs-208'),2,'lunch',pg_temp.sid('recipe:Turkey and hummus wrap'),1.2,1),
(pg_temp.sid('mpti:208:2:dinner'),pg_temp.sid('mpt:tbfs-208'),2,'dinner',pg_temp.sid('recipe:Beef lomo saltado'),1.2,2),
(pg_temp.sid('mpti:208:2:snack'),pg_temp.sid('mpt:tbfs-208'),2,'snack',pg_temp.sid('recipe:Apple and peanut butter'),1.2,3),
(pg_temp.sid('mpti:208:3:breakfast'),pg_temp.sid('mpt:tbfs-208'),3,'breakfast',pg_temp.sid('recipe:Banana protein pancakes'),1.1,0),
(pg_temp.sid('mpti:208:3:lunch'),pg_temp.sid('mpt:tbfs-208'),3,'lunch',pg_temp.sid('recipe:Quinoa and halloumi salad'),1.1,1),
(pg_temp.sid('mpti:208:3:dinner'),pg_temp.sid('mpt:tbfs-208'),3,'dinner',pg_temp.sid('recipe:Tomato mozzarella pizza'),1.1,2),
(pg_temp.sid('mpti:208:3:snack'),pg_temp.sid('mpt:tbfs-208'),3,'snack',pg_temp.sid('recipe:Rice cakes with almond butter'),1.1,3),
(pg_temp.sid('mpti:208:4:breakfast'),pg_temp.sid('mpt:tbfs-208'),4,'breakfast',pg_temp.sid('recipe:Smoked salmon bagel'),1.2,0),
(pg_temp.sid('mpti:208:4:lunch'),pg_temp.sid('mpt:tbfs-208'),4,'lunch',pg_temp.sid('recipe:Prawn noodle stir-fry'),1.2,1),
(pg_temp.sid('mpti:208:4:dinner'),pg_temp.sid('mpt:tbfs-208'),4,'dinner',pg_temp.sid('recipe:Salmon rice bowl'),1.2,2),
(pg_temp.sid('mpti:208:4:snack'),pg_temp.sid('mpt:tbfs-208'),4,'snack',pg_temp.sid('recipe:Hummus and veg sticks'),1.2,3),
(pg_temp.sid('mpti:208:5:breakfast'),pg_temp.sid('mpt:tbfs-208'),5,'breakfast',pg_temp.sid('recipe:Scrambled eggs on sourdough'),1.2,0),
(pg_temp.sid('mpti:208:5:lunch'),pg_temp.sid('mpt:tbfs-208'),5,'lunch',pg_temp.sid('recipe:Lentil and vegetable soup'),1.2,1),
(pg_temp.sid('mpti:208:5:dinner'),pg_temp.sid('mpt:tbfs-208'),5,'dinner',pg_temp.sid('recipe:BBQ pulled pork sandwich with pineapple slaw'),1.2,2),
(pg_temp.sid('mpti:208:5:snack'),pg_temp.sid('mpt:tbfs-208'),5,'snack',pg_temp.sid('recipe:Dark chocolate and almonds'),1.2,3),
(pg_temp.sid('mpti:208:6:breakfast'),pg_temp.sid('mpt:tbfs-208'),6,'breakfast',pg_temp.sid('recipe:Protein overnight oats'),1.0,0),
(pg_temp.sid('mpti:208:6:lunch'),pg_temp.sid('mpt:tbfs-208'),6,'lunch',pg_temp.sid('recipe:Chicken burrito bowl'),1.0,1),
(pg_temp.sid('mpti:208:6:dinner'),pg_temp.sid('mpt:tbfs-208'),6,'dinner',pg_temp.sid('recipe:Lemon parmesan chicken pasta'),1.0,2),
(pg_temp.sid('mpti:208:6:snack'),pg_temp.sid('mpt:tbfs-208'),6,'snack',pg_temp.sid('recipe:Apple and peanut butter'),1.0,3),
(pg_temp.sid('mpti:208:7:breakfast'),pg_temp.sid('mpt:tbfs-208'),7,'breakfast',pg_temp.sid('recipe:Greek yogurt power bowl'),1.1,0),
(pg_temp.sid('mpti:208:7:lunch'),pg_temp.sid('mpt:tbfs-208'),7,'lunch',pg_temp.sid('recipe:Tuna and chickpea salad'),1.1,1),
(pg_temp.sid('mpti:208:7:dinner'),pg_temp.sid('mpt:tbfs-208'),7,'dinner',pg_temp.sid('recipe:Tomato mozzarella pizza'),1.1,2),
(pg_temp.sid('mpti:208:7:snack'),pg_temp.sid('mpt:tbfs-208'),7,'snack',pg_temp.sid('recipe:Rice cakes with almond butter'),1.1,3),
(pg_temp.sid('mpti:207:1:breakfast'),pg_temp.sid('mpt:tbfs-207'),1,'breakfast',pg_temp.sid('recipe:Veggie egg-white omelette'),1.2,0),
(pg_temp.sid('mpti:207:1:lunch'),pg_temp.sid('mpt:tbfs-207'),1,'lunch',pg_temp.sid('recipe:Turkey and hummus wrap'),1.2,1),
(pg_temp.sid('mpti:207:1:dinner'),pg_temp.sid('mpt:tbfs-207'),1,'dinner',pg_temp.sid('recipe:Salmon tacos with crunchy slaw'),1.2,2),
(pg_temp.sid('mpti:207:1:snack'),pg_temp.sid('mpt:tbfs-207'),1,'snack',pg_temp.sid('recipe:Cottage cheese and pineapple'),1.2,3),
(pg_temp.sid('mpti:207:2:breakfast'),pg_temp.sid('mpt:tbfs-207'),2,'breakfast',pg_temp.sid('recipe:Banana protein pancakes'),0.9,0),
(pg_temp.sid('mpti:207:2:lunch'),pg_temp.sid('mpt:tbfs-207'),2,'lunch',pg_temp.sid('recipe:Quinoa and halloumi salad'),0.9,1),
(pg_temp.sid('mpti:207:2:dinner'),pg_temp.sid('mpt:tbfs-207'),2,'dinner',pg_temp.sid('recipe:Mediterranean turkey meatball bowl'),0.9,2),
(pg_temp.sid('mpti:207:2:snack'),pg_temp.sid('mpt:tbfs-207'),2,'snack',pg_temp.sid('recipe:Protein shake and banana'),0.9,3),
(pg_temp.sid('mpti:207:3:breakfast'),pg_temp.sid('mpt:tbfs-207'),3,'breakfast',pg_temp.sid('recipe:Smoked salmon bagel'),1.0,0),
(pg_temp.sid('mpti:207:3:lunch'),pg_temp.sid('mpt:tbfs-207'),3,'lunch',pg_temp.sid('recipe:Prawn noodle stir-fry'),1.0,1),
(pg_temp.sid('mpti:207:3:dinner'),pg_temp.sid('mpt:tbfs-207'),3,'dinner',pg_temp.sid('recipe:Creamy garlic and herb pasta'),1.0,2),
(pg_temp.sid('mpti:207:3:snack'),pg_temp.sid('mpt:tbfs-207'),3,'snack',pg_temp.sid('recipe:Skyr with berries and almonds'),1.0,3),
(pg_temp.sid('mpti:207:4:breakfast'),pg_temp.sid('mpt:tbfs-207'),4,'breakfast',pg_temp.sid('recipe:Scrambled eggs on sourdough'),1.1,0),
(pg_temp.sid('mpti:207:4:lunch'),pg_temp.sid('mpt:tbfs-207'),4,'lunch',pg_temp.sid('recipe:Lentil and vegetable soup'),1.1,1),
(pg_temp.sid('mpti:207:4:dinner'),pg_temp.sid('mpt:tbfs-207'),4,'dinner',pg_temp.sid('recipe:Beef cevapi with pita and yogurt'),1.1,2),
(pg_temp.sid('mpti:207:4:snack'),pg_temp.sid('mpt:tbfs-207'),4,'snack',pg_temp.sid('recipe:Boiled eggs and edamame'),1.1,3),
(pg_temp.sid('mpti:207:5:breakfast'),pg_temp.sid('mpt:tbfs-207'),5,'breakfast',pg_temp.sid('recipe:Protein overnight oats'),0.8,0),
(pg_temp.sid('mpti:207:5:lunch'),pg_temp.sid('mpt:tbfs-207'),5,'lunch',pg_temp.sid('recipe:Chicken burrito bowl'),0.8,1),
(pg_temp.sid('mpti:207:5:dinner'),pg_temp.sid('mpt:tbfs-207'),5,'dinner',pg_temp.sid('recipe:Chicken panang curry'),0.8,2),
(pg_temp.sid('mpti:207:5:snack'),pg_temp.sid('mpt:tbfs-207'),5,'snack',pg_temp.sid('recipe:Cottage cheese and pineapple'),0.8,3),
(pg_temp.sid('mpti:207:6:breakfast'),pg_temp.sid('mpt:tbfs-207'),6,'breakfast',pg_temp.sid('recipe:Greek yogurt power bowl'),1.0,0),
(pg_temp.sid('mpti:207:6:lunch'),pg_temp.sid('mpt:tbfs-207'),6,'lunch',pg_temp.sid('recipe:Tuna and chickpea salad'),1.0,1),
(pg_temp.sid('mpti:207:6:dinner'),pg_temp.sid('mpt:tbfs-207'),6,'dinner',pg_temp.sid('recipe:Salmon tacos with crunchy slaw'),1.0,2),
(pg_temp.sid('mpti:207:6:snack'),pg_temp.sid('mpt:tbfs-207'),6,'snack',pg_temp.sid('recipe:Protein shake and banana'),1.0,3),
(pg_temp.sid('mpti:207:7:breakfast'),pg_temp.sid('mpt:tbfs-207'),7,'breakfast',pg_temp.sid('recipe:Veggie egg-white omelette'),1.1,0),
(pg_temp.sid('mpti:207:7:lunch'),pg_temp.sid('mpt:tbfs-207'),7,'lunch',pg_temp.sid('recipe:Turkey and hummus wrap'),1.1,1),
(pg_temp.sid('mpti:207:7:dinner'),pg_temp.sid('mpt:tbfs-207'),7,'dinner',pg_temp.sid('recipe:Creamy garlic and herb pasta'),1.1,2),
(pg_temp.sid('mpti:207:7:snack'),pg_temp.sid('mpt:tbfs-207'),7,'snack',pg_temp.sid('recipe:Skyr with berries and almonds'),1.1,3),
(pg_temp.sid('mpti:206:1:breakfast'),pg_temp.sid('mpt:tbfs-206'),1,'breakfast',pg_temp.sid('recipe:Banana protein pancakes'),1.3,0),
(pg_temp.sid('mpti:206:1:lunch'),pg_temp.sid('mpt:tbfs-206'),1,'lunch',pg_temp.sid('recipe:Quinoa and halloumi salad'),1.3,1),
(pg_temp.sid('mpti:206:1:dinner'),pg_temp.sid('mpt:tbfs-206'),1,'dinner',pg_temp.sid('recipe:Baked sweet and sour chicken'),1.3,2),
(pg_temp.sid('mpti:206:1:snack'),pg_temp.sid('mpt:tbfs-206'),1,'snack',pg_temp.sid('recipe:Apple and peanut butter'),1.3,3),
(pg_temp.sid('mpti:206:2:breakfast'),pg_temp.sid('mpt:tbfs-206'),2,'breakfast',pg_temp.sid('recipe:Smoked salmon bagel'),1.4,0),
(pg_temp.sid('mpti:206:2:lunch'),pg_temp.sid('mpt:tbfs-206'),2,'lunch',pg_temp.sid('recipe:Prawn noodle stir-fry'),1.4,1),
(pg_temp.sid('mpti:206:2:dinner'),pg_temp.sid('mpt:tbfs-206'),2,'dinner',pg_temp.sid('recipe:Lean ground beef tacos'),1.4,2),
(pg_temp.sid('mpti:206:2:snack'),pg_temp.sid('mpt:tbfs-206'),2,'snack',pg_temp.sid('recipe:Rice cakes with almond butter'),1.4,3),
(pg_temp.sid('mpti:206:3:breakfast'),pg_temp.sid('mpt:tbfs-206'),3,'breakfast',pg_temp.sid('recipe:Scrambled eggs on sourdough'),1.3,0),
(pg_temp.sid('mpti:206:3:lunch'),pg_temp.sid('mpt:tbfs-206'),3,'lunch',pg_temp.sid('recipe:Lentil and vegetable soup'),1.3,1),
(pg_temp.sid('mpti:206:3:dinner'),pg_temp.sid('mpt:tbfs-206'),3,'dinner',pg_temp.sid('recipe:Smoky black bean burger'),1.3,2),
(pg_temp.sid('mpti:206:3:snack'),pg_temp.sid('mpt:tbfs-206'),3,'snack',pg_temp.sid('recipe:Hummus and veg sticks'),1.3,3),
(pg_temp.sid('mpti:206:4:breakfast'),pg_temp.sid('mpt:tbfs-206'),4,'breakfast',pg_temp.sid('recipe:Protein overnight oats'),1.1,0),
(pg_temp.sid('mpti:206:4:lunch'),pg_temp.sid('mpt:tbfs-206'),4,'lunch',pg_temp.sid('recipe:Chicken burrito bowl'),1.1,1),
(pg_temp.sid('mpti:206:4:dinner'),pg_temp.sid('mpt:tbfs-206'),4,'dinner',pg_temp.sid('recipe:Thai basil chicken with rice'),1.1,2),
(pg_temp.sid('mpti:206:4:snack'),pg_temp.sid('mpt:tbfs-206'),4,'snack',pg_temp.sid('recipe:Dark chocolate and almonds'),1.1,3),
(pg_temp.sid('mpti:206:5:breakfast'),pg_temp.sid('mpt:tbfs-206'),5,'breakfast',pg_temp.sid('recipe:Greek yogurt power bowl'),1.4,0),
(pg_temp.sid('mpti:206:5:lunch'),pg_temp.sid('mpt:tbfs-206'),5,'lunch',pg_temp.sid('recipe:Tuna and chickpea salad'),1.4,1),
(pg_temp.sid('mpti:206:5:dinner'),pg_temp.sid('mpt:tbfs-206'),5,'dinner',pg_temp.sid('recipe:Lighter Swedish meatballs'),1.4,2),
(pg_temp.sid('mpti:206:5:snack'),pg_temp.sid('mpt:tbfs-206'),5,'snack',pg_temp.sid('recipe:Apple and peanut butter'),1.4,3),
(pg_temp.sid('mpti:206:6:breakfast'),pg_temp.sid('mpt:tbfs-206'),6,'breakfast',pg_temp.sid('recipe:Veggie egg-white omelette'),1.5,0),
(pg_temp.sid('mpti:206:6:lunch'),pg_temp.sid('mpt:tbfs-206'),6,'lunch',pg_temp.sid('recipe:Turkey and hummus wrap'),1.5,1),
(pg_temp.sid('mpti:206:6:dinner'),pg_temp.sid('mpt:tbfs-206'),6,'dinner',pg_temp.sid('recipe:Baked sweet and sour chicken'),1.5,2),
(pg_temp.sid('mpti:206:6:snack'),pg_temp.sid('mpt:tbfs-206'),6,'snack',pg_temp.sid('recipe:Rice cakes with almond butter'),1.5,3),
(pg_temp.sid('mpti:206:7:breakfast'),pg_temp.sid('mpt:tbfs-206'),7,'breakfast',pg_temp.sid('recipe:Banana protein pancakes'),1.2,0),
(pg_temp.sid('mpti:206:7:lunch'),pg_temp.sid('mpt:tbfs-206'),7,'lunch',pg_temp.sid('recipe:Quinoa and halloumi salad'),1.2,1),
(pg_temp.sid('mpti:206:7:dinner'),pg_temp.sid('mpt:tbfs-206'),7,'dinner',pg_temp.sid('recipe:Smoky black bean burger'),1.2,2),
(pg_temp.sid('mpti:206:7:snack'),pg_temp.sid('mpt:tbfs-206'),7,'snack',pg_temp.sid('recipe:Hummus and veg sticks'),1.2,3)
on conflict (id) do nothing;


commit;
