-- MY GYM London - migration: exercises from the client workout sheets
-- Source: WORKOUT PICTURES/exercise_list.md. Paste into Supabase Dashboard -> SQL Editor -> Run (safe to re-run).
-- Adds 108 exercises (no repeats of the ones already in the library) and uses the plain
-- name "Jumping jacks" in the Fat-Burn Circuit so it links to the library.

begin;

insert into public.exercises (name, muscle_group, equipment, how_to, sort) values
('Sled push', 'Cardio', 'Sled', 'Hands on the uprights, low hips, drive the sled forward with short, powerful steps.', 71),
('Sled pull', 'Cardio', 'Sled', 'Hold the rope or straps, walk backwards or lean back and pull hand over hand to bring the sled to you.', 72),
('Battle rope waves', 'Cardio', 'Battle rope', 'Athletic stance, brace the core and whip both ends up and down in fast alternating waves.', 73),
('Medicine ball slam', 'Cardio', 'Medicine ball', 'Lift the ball overhead, then slam it down hard in front of your feet, squat to pick it up and repeat.', 74),
('Jumping jacks', 'Cardio', 'Bodyweight', 'Jump the feet wide while the arms go overhead, then jump back together. Step out one leg at a time for a low-impact version.', 75),
('Boxing rounds', 'Cardio', 'Boxing bag', 'Hands up, stay light on the feet and throw jab, cross and hook combinations for the full round.', 76),
('Treadmill run', 'Cardio', 'Treadmill', 'Run at a steady pace you can breathe at, land softly under the hips and keep the shoulders relaxed.', 77),
('Skipping', 'Cardio', 'Skipping rope', 'Turn the rope from the wrists and jump low on the balls of the feet, one jump per turn.', 78),
('Burpee', 'Cardio', 'Bodyweight', 'Squat down, kick the feet back to a plank, chest to the floor, jump the feet in and finish with a jump.', 79),
('Box jump', 'Cardio', 'Box', 'Swing the arms, jump up onto the box with both feet and land softly, then step back down.', 80),
('Broad jump', 'Cardio', 'Bodyweight', 'Swing the arms, jump forward as far as you can and land softly with bent knees.', 81),
('Jump squat', 'Cardio', 'Bodyweight', 'Squat down, then explode up into a jump and land softly straight into the next squat.', 82),
('High knees', 'Cardio', 'Bodyweight', 'Run on the spot driving the knees up to hip height, pumping the arms.', 83),
('Agility ladder drills', 'Cardio', 'Bodyweight', 'Move quickly through the agility ladder with fast, light foot patterns, one foot in each square.', 84),
('Side shuffles', 'Cardio', 'Bodyweight', 'In a half squat, shuffle sideways without crossing the feet, then return the same way.', 85),
('Landmine punch', 'Cardio', 'Landmine', 'Hold the end of the bar at the shoulder and punch it up and forward, rotating the hips.', 86),
('Power bag drag', 'Full body', 'Power bag', 'Grip the bag, stay low and drag or pull it across the floor in a straight line.', 87),
('Bodyweight squat', 'Legs', 'Bodyweight', 'Feet shoulder-width apart, sit the hips back and down, chest tall, then stand up.', 88),
('TRX squat', 'Legs', 'TRX', 'Hold the TRX handles, lean back with straight arms and squat down, using the straps for balance.', 89),
('Dumbbell squat', 'Legs', 'Dumbbell', 'Hold dumbbells at the sides or shoulders, squat to depth with an upright chest and drive up.', 90),
('Kettlebell front squat', 'Legs', 'Kettlebell', 'Rack the kettlebell at the shoulder, elbow in, and squat down keeping the torso upright.', 91),
('Front squat', 'Legs', 'Barbell', 'Bar across the front of the shoulders, elbows high, squat to depth and drive up.', 92),
('Sumo squat', 'Legs', 'Dumbbell', 'Wide stance, toes out, hold one dumbbell between the legs and squat straight down.', 93),
('Bosu squat', 'Legs', 'Bosu', 'Stand on the Bosu, or on the flat side, and squat slowly while keeping the knees steady.', 94),
('Squat hold', 'Legs', 'Bodyweight', 'Sit into the bottom of a squat and hold it still, chest up, weight through the heels.', 95),
('Squat pulse', 'Legs', 'Bodyweight', 'Stay low in a squat and make small up-and-down pulses without standing all the way up.', 96),
('Wall sit', 'Legs', 'Bodyweight', 'Back flat on the wall, thighs parallel to the floor, hold the position.', 97),
('Side lunge', 'Legs', 'Bodyweight', 'Step wide to the side, sit back into that hip with the other leg straight, push back to the middle.', 98),
('Dumbbell side lunge', 'Legs', 'Dumbbell', 'Hold a dumbbell at the chest, step wide to the side and sit back into the hip, push back to the middle.', 99),
('TRX side lunge', 'Legs', 'TRX', 'Hold the TRX handles for balance, step to the side into a lunge and push back to the middle.', 100),
('Dumbbell lunge', 'Legs', 'Dumbbell', 'Dumbbells at the sides, step forward or back into a lunge, lower the back knee and return.', 101),
('Lunge and curl', 'Legs', 'Dumbbell', 'Lower into a lunge, and as you stand up curl the dumbbells to the shoulders.', 102),
('Lunge and press', 'Full body', 'Dumbbell', 'Lunge forward or to the side with the dumbbells at the shoulders, and press them overhead as you stand up.', 103),
('Reverse lunge with knee drive', 'Legs', 'Bodyweight', 'Step back into a lunge, then drive the back knee up to hip height as you stand.', 104),
('Smith lunge', 'Legs', 'Smith bar', 'Bar on the upper back, step forward or back into a lunge and push through the front heel.', 105),
('Smith deadlift', 'Legs', 'Smith bar', 'Feet under the bar, hinge with a flat back, grip and stand up, sliding the bar up the legs.', 106),
('Sumo deadlift', 'Legs', 'Barbell', 'Wide stance, toes out, grip inside the knees, push the floor away and stand tall.', 107),
('Shoulder bridge', 'Glutes', 'Bodyweight', 'Lie on your back, feet flat, lift the hips until shoulders, hips and knees line up and squeeze the glutes.', 108),
('Single-leg hip raise', 'Glutes', 'Bodyweight', 'Lie on your back with one foot on the floor and the other leg straight, lift the hips and lower slowly.', 109),
('Cable hamstring curl', 'Legs', 'Cable', 'Strap the cable to the ankle, face the machine and curl the heel towards the glute, return slowly.', 110),
('Side-lying inner thigh raise', 'Legs', 'Bodyweight', 'Lie on your side with the top leg bent in front and lift the bottom leg up and down.', 111),
('Donkey kick', 'Glutes', 'Bodyweight', 'On hands and knees, kick one heel up towards the ceiling, keeping the back flat, and lower slowly.', 112),
('Fire hydrant', 'Glutes', 'Bodyweight', 'On hands and knees, lift one knee out to the side to hip height without rotating the back.', 113),
('Glute kickback', 'Glutes', 'Bodyweight', 'On hands and knees, or standing, kick one leg back and squeeze the glute at the top.', 114),
('TRX squat and row', 'Full body', 'TRX', 'Lean back on the straps, squat down, then stand and row the handles to the chest in one movement.', 115),
('Good morning', 'Back', 'Barbell', 'Bar on the upper back, soft knees, push the hips back until the torso is near parallel, then stand.', 116),
('Incline Smith press', 'Chest', 'Smith bar', 'Bench at 30 degrees under the bar, lower to the upper chest and press up.', 117),
('Incline barbell press', 'Chest', 'Barbell', 'Bench at 30 degrees, lower the bar to the upper chest and press up over the shoulders.', 118),
('Reverse-grip dumbbell press', 'Chest', 'Dumbbell', 'Palms facing you, lower the dumbbells to the chest and press up, elbows tucked in.', 119),
('Close-grip dumbbell press', 'Chest', 'Dumbbell', 'Dumbbells touching, press them up from the chest with the elbows in, squeezing the chest and triceps.', 120),
('Dumbbell fly', 'Chest', 'Dumbbell', 'Lie on a bench, open the arms wide with soft elbows until you feel a stretch, then bring them together.', 121),
('Cable crossover', 'Chest', 'Cable', 'Stand between high pulleys, step forward and bring the handles down and together in front of the hips.', 122),
('Knee push-up', 'Chest', 'Bodyweight', 'Hands under shoulders and knees on the floor, body straight from knees to head, lower the chest and push back.', 123),
('TRX push-up', 'Chest', 'TRX', 'Hands in the TRX handles, body in a straight line, lower the chest between the hands and push back.', 124),
('Dip', 'Chest', 'Bodyweight', 'Grip the dip bars, lower until the elbows are at 90 degrees and press back up.', 125),
('Bench dip', 'Arms', 'Bodyweight', 'Hands on a bench behind you, lower the hips by bending the elbows, then press back up.', 126),
('Lying triceps extension', 'Arms', 'Dumbbell', 'Lie on a bench, bend the elbows to lower the weights beside the head, then extend the arms.', 127),
('Triceps kickback', 'Arms', 'Dumbbell', 'Hinge forward with the upper arm parallel to the floor and straighten the elbow behind you.', 128),
('Arnold press', 'Shoulders', 'Dumbbell', 'Start with palms facing you at the chest and rotate them forward as you press the dumbbells overhead.', 129),
('Dumbbell floor press', 'Chest', 'Dumbbell', 'Lie on the floor, lower the dumbbells until the upper arms touch the floor and press up.', 130),
('Plate press', 'Chest', 'Plate', 'Hold a plate at the chest and press it straight out in front, squeezing the chest.', 131),
('Glute bridge press', 'Chest', 'Dumbbell', 'Hold a bridge on your back and press the dumbbells up from the chest.', 132),
('Renegade row', 'Back', 'Dumbbell', 'In a push-up position on the dumbbells, row one dumbbell to the hip while keeping the hips still.', 133),
('Straight-arm pulldown', 'Back', 'Cable', 'Stand facing a high pulley, arms straight, press the bar or rope down to the thighs and return slowly.', 134),
('TRX row', 'Back', 'TRX', 'Lean back holding the TRX handles, body straight, pull the chest to the hands and lower slowly.', 135),
('Landmine row', 'Back', 'Landmine', 'Straddle the bar, hinge to a flat back and row the end of the bar to the chest.', 136),
('Dumbbell bent-over row', 'Back', 'Dumbbell', 'Hinge to a flat back and row both dumbbells to the hips, squeezing the shoulder blades.', 137),
('Inverted row', 'Back', 'Smith bar', 'Lie under a low bar, grip it and pull the chest to the bar with the body straight.', 138),
('Dumbbell reverse fly', 'Shoulders', 'Dumbbell', 'Hinge forward, or lie on an incline bench, and raise the dumbbells out to the sides with soft elbows.', 139),
('TRX reverse fly', 'Shoulders', 'TRX', 'Lean back holding the TRX handles and open the arms wide, squeezing the shoulder blades.', 140),
('Back extension', 'Back', 'Bodyweight', 'Face down over a bench or bench edge, lift the chest until the body is straight and lower slowly.', 141),
('Dumbbell pullover', 'Back', 'Dumbbell', 'Lie across a bench holding one dumbbell, lower it back over the head with straight arms and pull it over the chest.', 142),
('Swimmers', 'Back', 'Bodyweight', 'Lie face down and alternate lifting opposite arm and leg in a flutter-style swimming motion.', 143),
('Upright row', 'Shoulders', 'Barbell', 'Pull the bar up close to the body to chest height, elbows leading, and lower slowly.', 144),
('Dumbbell front raise', 'Shoulders', 'Dumbbell', 'Raise the dumbbell straight in front to shoulder height and lower slowly.', 145),
('Rotator cuff external rotation', 'Shoulders', 'Cable', 'Elbow at your side bent to 90 degrees, rotate the hand outwards against the light cable, then return.', 146),
('Dumbbell shrug', 'Shoulders', 'Dumbbell', 'Hold the dumbbells at the sides and lift the shoulders straight up to the ears, pause and lower.', 147),
('Incline dumbbell curl', 'Arms', 'Dumbbell', 'Sit back on an incline bench with the arms hanging, curl the dumbbells up and lower slowly.', 148),
('Barbell curl', 'Arms', 'Barbell', 'Elbows pinned to the sides, curl the bar to the shoulders and lower under control.', 149),
('Cable rope curl', 'Arms', 'Cable', 'Hold the rope at a low pulley and curl to the shoulders, keeping the elbows still.', 150),
('Cable forearm curl', 'Arms', 'Cable', 'Rest the forearm on the thigh or bench and curl the wrist up against the low cable.', 151),
('TRX biceps curl', 'Arms', 'TRX', 'Lean back holding the TRX handles with palms up and curl the hands to the head.', 152),
('Curl and press', 'Arms', 'Dumbbell', 'Curl the dumbbells to the shoulders and press straight into an overhead press, then lower.', 153),
('Dumbbell clean and press', 'Full body', 'Dumbbell', 'Pull the dumbbells from the floor to the shoulders in one move, then press them overhead.', 154),
('Barbell clean and press', 'Full body', 'Barbell', 'Pull the bar from the floor to the shoulders in one explosive move, then press it overhead.', 155),
('Leg drop', 'Core', 'Bodyweight', 'Lie on your back with the legs straight up, lower them slowly towards the floor without arching the back.', 156),
('Medicine ball sit-up', 'Core', 'Medicine ball', 'Sit up holding the ball and bring it overhead or pass it to your feet at the top.', 157),
('Medicine ball crunch', 'Core', 'Medicine ball', 'Lie on your back with the knees bent and the ball over the knees, crunch up to meet the ball.', 158),
('Sit-up', 'Core', 'Bodyweight', 'Lie on your back with the knees bent, curl all the way up to sitting and lower with control.', 159),
('Side crunch', 'Core', 'Bodyweight', 'Lie on your side or on your back and bring the elbow towards the knee on the same side.', 160),
('Landmine twist', 'Core', 'Landmine', 'Hold the end of the bar at the chest and rotate it from side to side with straight arms, pivoting the feet.', 161),
('Bird dog', 'Core', 'Bodyweight', 'On hands and knees, reach one arm and the opposite leg out long, hold, and swap sides.', 162),
('Side plank', 'Core', 'Bodyweight', 'On one forearm, lift the hips so the body is a straight line and hold. Drop the bottom knee to make it easier.', 163),
('Plank shoulder tap', 'Core', 'Bodyweight', 'In a high plank, tap each shoulder in turn while keeping the hips from rocking.', 164),
('Ab rollout', 'Core', 'Barbell', 'Kneel holding the wheel or barbell, roll out with a braced core and pull back without sagging the hips.', 165),
('V-up', 'Core', 'Bodyweight', 'Lie flat and lift the legs and chest together to meet in a V, then lower slowly.', 166),
('Hanging leg raise', 'Core', 'Pull-up bar', 'Hang from the bar and raise straight legs to hip height or higher, lowering without swinging.', 167),
('Turkish get-up', 'Full body', 'Kettlebell', 'Lie on your back holding the kettlebell overhead and stand up in controlled steps, keeping the arm straight.', 168),
('Lying leg raise', 'Core', 'Bodyweight', 'Lie on your back and lift the straight legs to vertical, lowering slowly without arching.', 169),
('Butterfly sit-up', 'Core', 'Bodyweight', 'Lie with the soles of the feet together and the knees out, sit up and reach towards the feet.', 170),
('Crunch', 'Core', 'Bodyweight', 'Lie on your back with the knees bent, lift the shoulders off the floor and lower slowly.', 171),
('Flutter kicks', 'Core', 'Bodyweight', 'Lie on your back with the legs just off the floor and kick them up and down in small quick movements.', 172),
('Scissor kicks', 'Core', 'Bodyweight', 'Lie on your back with the legs raised and cross them over each other in a scissor motion.', 173),
('Dumbbell side bend', 'Core', 'Dumbbell', 'Hold a dumbbell in one hand and lean to that side, then return upright using the opposite side of the waist.', 174),
('TRX pike', 'Core', 'TRX', 'Feet in the TRX straps in a plank, lift the hips up towards the ceiling and lower back down.', 175),
('Ankle touches', 'Core', 'Bodyweight', 'Lie with the knees bent and reach each hand to the same-side ankle with a small side crunch.', 176),
('Swiss ball tuck', 'Core', 'Swiss ball', 'With the feet on the ball in a plank, pull the knees in towards the chest and roll back out.', 177),
('Knee tuck', 'Core', 'Bodyweight', 'Lie on your back and pull the knees up to the chest, lowering the feet without touching the floor.', 178)
on conflict (name) do update set muscle_group = excluded.muscle_group, equipment = excluded.equipment,
  how_to = excluded.how_to, sort = excluded.sort;

update public.workout_templates
  set exercises = replace(exercises::text, 'Jumping jacks (or step jacks)', 'Jumping jacks')::jsonb
  where created_by is null and exercises::text like '%Jumping jacks (or step jacks)%';

commit;
